;(function($){var fls=!1,nll=null,prsflt=parseFloat,frCrCd=String.fromCharCode,mathmn=Math.min,rxLastNr=/(-?\d+\.?\d*)$/g,sCharOrder,aAllChars=[],aOrderChar,bDoubles,iReplace=0x2500,oReplace={},rxNotLatin;if(!Array.indexOf){Array.prototype.indexOf=function(o){for(var i=0,l=this.length;i<l;i++)if(this[i]==o)return i;return-1;}}
for(var i=32,s=frCrCd(i),len=255;i<len;i++,s=frCrCd(i).toLowerCase()){if(aAllChars.indexOf(s)!==-1)aAllChars.push(s);}
aAllChars.sort();$.tinysort={id:'TinySort',version:'1.3.27',copyright:'Copyright (c) 2008-2012 Ron Valstar',uri:'http://tinysort.sjeiti.com/',licenced:{MIT:'http://www.opensource.org/licenses/mit-license.php',GPL:'http://www.gnu.org/licenses/gpl.html'},defaults:{order:'asc',attr:nll,data:nll,useVal:fls,place:'start',returns:fls,cases:fls,forceStrings:fls,sortFunction:nll,charOrder:sCharOrder}};$.fn.extend({tinysort:function(_find,_settings){if(_find&&typeof(_find)!='string'){_settings=_find;_find=nll;}
var oSettings=$.extend({},$.tinysort.defaults,_settings),sParent,oThis=this,iLen=$(this).length,oElements={},bFind=!(!_find||_find==''),bAttr=!(oSettings.attr===nll||oSettings.attr==""),bData=oSettings.data!==nll,bFilter=bFind&&_find[0]==':',$Filter=bFilter?oThis.filter(_find):oThis,fnSort=oSettings.sortFunction,iAsc=oSettings.order=='asc'?1:-1,aNewOrder=[];if(oSettings.charOrder!=sCharOrder){sCharOrder=oSettings.charOrder;if(!oSettings.charOrder){bDoubles=false;iReplace=0x2500;oReplace={};rxNotLatin=aOrderChar=nll;}else{aOrderChar=aAllChars.slice(0);bDoubles=false;for(var
aCharNotLatin=[],fnAddNonLatinChar=function(key,nonLatin){aCharNotLatin.push(nonLatin);oReplace[oSettings.cases?key:key.toLowerCase()]=nonLatin;},sAllCharNotLatin='',sCharLatin='z',l=sCharOrder.length,j,m,i=0;i<l;i++){var sChar=sCharOrder[i],iChar=sChar.charCodeAt(),bIsLatin=iChar>96&&iChar<123;if(!bIsLatin){if(sChar=='['){var iCharNotLatin=aCharNotLatin.length,sLastChar=iCharNotLatin?aCharNotLatin[iCharNotLatin-1]:sCharLatin,sReplaces=sCharOrder.substr(i+1).match(/[^\]]*/)[0],aDoubles=sReplaces.match(/{[^}]*}/g);if(aDoubles){for(j=0,m=aDoubles.length;j<m;j++){var sCode=aDoubles[j];i+=sCode.length;sReplaces=sReplaces.replace(sCode,'');fnAddNonLatinChar(sCode.replace(/[{}]/g,''),sLastChar);bDoubles=true;}}
for(j=0,m=sReplaces.length;j<m;j++)fnAddNonLatinChar(sLastChar,sReplaces[j]);i+=sReplaces.length+1;}else if(sChar=='{'){var sDouble=sCharOrder.substr(i+1).match(/[^}]*/)[0];fnAddNonLatinChar(sDouble,frCrCd(iReplace++));i+=sDouble.length+1;bDoubles=true;}else{aCharNotLatin.push(sChar);}}
if(aCharNotLatin.length&&(bIsLatin||i===l-1)){var sCharNotLatin=aCharNotLatin.join('');sAllCharNotLatin+=sCharNotLatin;$.each(sCharNotLatin,function(j,s){aOrderChar.splice(aOrderChar.indexOf(s),1);});var aParse=aCharNotLatin.slice(0);aParse.splice(0,0,aOrderChar.indexOf(sCharLatin)+1,0);Array.prototype.splice.apply(aOrderChar,aParse);aCharNotLatin.length=0;}
if(i+1===l)rxNotLatin=new RegExp('['+sAllCharNotLatin+']','gi');else if(bIsLatin)sCharLatin=sChar;}}}
if(!fnSort)fnSort=oSettings.order=='rand'?function(){return Math.random()<.5?1:-1;}:function(a,b){var bNumeric=fls,sA=!oSettings.cases?toLowerCase(a.s):a.s,sB=!oSettings.cases?toLowerCase(b.s):b.s;if(!oSettings.forceStrings){var aAnum=sA&&sA.match(rxLastNr),aBnum=sB&&sB.match(rxLastNr);if(aAnum&&aBnum){var sAprv=sA.substr(0,sA.length-aAnum[0].length),sBprv=sB.substr(0,sB.length-aBnum[0].length);if(sAprv==sBprv){bNumeric=!fls;sA=prsflt(aAnum[0]);sB=prsflt(aBnum[0]);}}}
var iReturn=iAsc*(sA<sB?-1:(sA>sB?1:0));if(!bNumeric&&oSettings.charOrder){if(bDoubles){for(var s in oReplace){var o=oReplace[s];sA=sA.replace(s,o);sB=sB.replace(s,o);}}
if(sA.match(rxNotLatin)!==nll||sB.match(rxNotLatin)!==nll){for(var k=0,l=mathmn(sA.length,sB.length);k<l;k++){var iAchr=aOrderChar.indexOf(sA[k]),iBchr=aOrderChar.indexOf(sB[k]);if(iReturn=iAsc*(iAchr<iBchr?-1:(iAchr>iBchr?1:0)))break;}}}
return iReturn;};oThis.each(function(i,el){var $Elm=$(el),mElmOrSub=bFind?(bFilter?$Filter.filter(el):$Elm.find(_find)):$Elm,sSort=bData?''+mElmOrSub.data(oSettings.data):(bAttr?mElmOrSub.attr(oSettings.attr):(oSettings.useVal?mElmOrSub.val():mElmOrSub.text())),mParent=$Elm.parent();if(!oElements[mParent])oElements[mParent]={s:[],n:[]};if(mElmOrSub.length>0)oElements[mParent].s.push({s:sSort,e:$Elm,n:i});else oElements[mParent].n.push({e:$Elm,n:i});});for(sParent in oElements)oElements[sParent].s.sort(fnSort);for(sParent in oElements){var oParent=oElements[sParent],aOrg=[],iLow=iLen,aCnt=[0,0],i;switch(oSettings.place){case'first':$.each(oParent.s,function(i,obj){iLow=mathmn(iLow,obj.n)});break;case'org':$.each(oParent.s,function(i,obj){aOrg.push(obj.n)});break;case'end':iLow=oParent.n.length;break;default:iLow=0;}
for(i=0;i<iLen;i++){var bSList=contains(aOrg,i)?!fls:i>=iLow&&i<iLow+oParent.s.length,mEl=(bSList?oParent.s:oParent.n)[aCnt[bSList?0:1]].e;mEl.parent().append(mEl);if(bSList||!oSettings.returns)aNewOrder.push(mEl.get(0));aCnt[bSList?0:1]++;}}
oThis.length=0;Array.prototype.push.apply(oThis,aNewOrder);return oThis;}});function toLowerCase(s){return s&&s.toLowerCase?s.toLowerCase():s;}
function contains(a,n){for(var i=0,l=a.length;i<l;i++)if(a[i]==n)return!fls;return fls;}
$.fn.TinySort=$.fn.Tinysort=$.fn.tsort=$.fn.tinysort;})(jQuery);