
var Share={sharePage:function(targetName,pub,pageUrl,pageTitle,tabId){var url,title,targets,target,shareUrl,mediaUrl;if(typeof targetName==='object'){shareObject=targetName;url=shareObject.pageUrl;title=encodeURIComponent(shareObject.pageTitle);targets=Preferences.getPreferredServicesDetails();target=targets[shareObject.targetName];if('mediaUrl'in shareObject){mediaUrl=shareObject.mediaUrl;}
targetName=shareObject.targetName;}else{url=encodeURIComponent(pageUrl);title=encodeURIComponent(pageTitle);targets=Preferences.getPreferredServicesDetails();target=targets[targetName];}
switch(targetName){case'pinterest':chrome.tabs.executeScript(null,{file:"js/ATX.chrome.content.pinterest.js"});break;default:if(["print","favorites","mailto"].indexOf(targetName)>-1){this._specialTarget(tabId,targetName,pub,url,title);}
else if(targetName=="more"){shareUrl="https://api.addthis.com/oexchange/0.8/forward/offer?url="+url;if(title)
shareUrl+="&title="+title;if(pub!==""&&pub!==null)
shareUrl+="&pubid="+pub;shareUrl+="&pco="+(!Preferences.isSocialServices()?Constants.CHROME_PCO:Constants.CHROME_PCO_WITH_SOCIAL);chrome.tabs.create({url:shareUrl});}
else if(target!==null){shareUrl=target.buildShareUrl(url,title,pub);chrome.tabs.create({url:shareUrl});}
break;}},guessImage:function(cb){chrome.tabs.getSelected(null,function(tab){chrome.tabs.sendRequest(tab.id,{greeting:"hello"},function(response){if(!response||!response.src){return cb(1,null);}else{return cb(null,response.src);}});});},shareToPinterest:function(pageUrl){if(typeof pageUrl==='object'&&'media'in pageUrl&&'url'in pageUrl){var shareObject=pageUrl;var url=this.formPinterestUrl(shareObject);chrome.tabs.create({url:url});}else{var that=this;var doneOnce=false;this.guessImage(function(err,mediaUrl){if(err){if(!doneOnce){doneOnce=true;alert('Can\'t find an image to pin. Try right-clicking on a specific image and selecting "AddThis: Pin to Pinterest"');}}
if(!err){var url=that.formPinterestUrl({url:pageUrl,media:mediaUrl});chrome.tabs.create({url:url});}});}},formPinterestUrl:function(shareObject){if(!shareObject||!('media'in shareObject&&'url'in shareObject)){}
var url='http://www.addthis.com/bookmark.php?';url+='pco='+ATX.constants.PCO;url+='&s=pinterest_share';if('pubid'in shareObject){url+='&pub='+shareObject.pubid;}
url+='&url='+encodeURIComponent(shareObject.url);var passthrough='media='+encodeURIComponent(shareObject.media)+'&url='+encodeURIComponent(shareObject.url);url+='&passthrough='+encodeURIComponent(passthrough);return url;},_specialTarget:function(tabId,target,pub,shareUrl,shareTitle){switch(target){case"print":var action_url="javascript:window.print();";chrome.tabs.update(tabId,{url:action_url});break;case"favorites":alert("Press <Control> + D to bookmark");break;case"mailto":chrome.tabs.update(tabId,{url:'mailto:?subject='+shareTitle+'&body='+shareUrl});break;default:return;}}};