
var isCtrl=false;var servicesExclude=["addressbar","facebook_comment","facebook_uncomment"];var bgpage=chrome.extension.getBackgroundPage();jQuery.fn.swapWith=function(to){return this.each(function(){var copy_to=$(to).clone(true);var copy_from=$(this).clone(true);$(to).replaceWith(copy_from);$(this).replaceWith(copy_to);});};$(document).ready(function(){if(localStorage["context_menu"]==undefined){localStorage["context_menu"]="true";}
if(localStorage["context_menu"]!=="true"){$("#chkContextMenu").removeAttr("checked");}
if(localStorage["context_menu_search"]==undefined){localStorage["context_menu_search"]="false";}
if(localStorage["context_menu_search"]!=="true"){localStorage["context_menu_search"]="false";}
if(localStorage["context_menu_search"]==="true"){$("#chkContextMenuSearch").attr("checked","checked");}
$(document).keydown(function(event){isCtrl=event.keyCode=='17'?true:false;});$(document).keyup(function(event){if(event.keyCode=='17'){isCtrl=false;}});$("#add-services-filter").focus(function(){$("#add-services-filter").val("");$('#add-services-filter').unbind('focus');});$("#add-services-filter").keyup(function(){var filterText=$("#add-services-filter").val();if(!filterText){$("#add-services").children().each(function(n,o){$(o).show();});}
else{$("#add-services").children().each(function(n,o){if(o.id.indexOf(filterText)>-1)
$(o).show();else
$(o).hide();});}});$("#btnOAuthFacebook").click(function(){if(!bgpage.FBHandler.isSession){bgpage.FBHandler.authenticate();}
else{bgpage.FBHandler.cleanAuthDetails();setButtonCSS("btnOAuthFacebook","Connect",{add:"btn-grn",remove:"btn-red"});$("#divFBUserInfo").hide("slow");}});$("#btnOAuthTwitter").click(function(){if(!bgpage.TwitterHandler.isSession){$("#btnOAuthTwitter").html("<span></span>");$('#btnOAuthTwitter').addClass("loading");$('#btnOAuthTwitter').attr("disabled",true);setTimeout(function(){if($('#btnOAuthTwitter').attr("class")=="btn-grn connect_word loading"){setButtonCSS("btnOAuthTwitter","Connect",{add:"btn-grn",remove:"btn-red"});$('#btnOAuthTwitter').attr("disabled",false);}},15000);bgpage.TwitterHandler.getToken();}
else{bgpage.TwitterHandler.cleanAuthDetails();setButtonCSS("btnOAuthTwitter","Connect",{add:"btn-grn",remove:"btn-red"});$("#divTwitterUserInfo").hide("slow");}});if(bgpage.Preferences.isSocialServices()||(bgpage.Preferences.isFBAuthPreference()&&bgpage.Preferences.isTwitterAuthPreference())){if(bgpage.FBHandler.isSession){setButtonCSS("btnOAuthFacebook","Disconnect",{add:"btn-red",remove:"btn-grn"});setUserInfo("btnOAuthFacebook");}
if(bgpage.TwitterHandler.isSession){setButtonCSS("btnOAuthTwitter","Disconnect",{add:"btn-red",remove:"btn-grn"});setUserInfo("btnOAuthTwitter");}!bgpage.Preferences.isFBAuthPreference()&&!bgpage.Preferences.isTwitterAuthPreference()?$("#chkSocialServices").attr("checked",""):$("#chkSocialServices").attr("checked","checked");}
if(bgpage.Preferences.isSocialServices()){if(bgpage.Preferences.isFBAuthPreference())
$("#chkFBAuth").attr("checked",true);if(bgpage.Preferences.isTwitterAuthPreference())
$("#chkTwitterAuth").attr("checked",true);}
toggleSocialServices(true);$("#submitbtn").click(function(){updateSSH();$(".savedChanges").html("Changes successfully saved.");$(".savedChanges").show("slow");setTimeout(function(){$(".savedChanges").hide("slow");},4000);bgpage.BootLoader.loadServices();updateContextMenuSettings();});$("#resetbtn").click(function(){var c=confirm("Are you sure you want to reset your services?");if(c){localStorage["addthis_sshp"]="facebook,twitter,email,print,gmail,stumbleupon,favorites,blogger,tumblr,pinterest,google";localStorage["addthis_sshp_reset"]="reset";location.reload();}
bgpage.BootLoader.loadServices();});$("#addServiceBtn").click(function(){var availSlots=$("#add-services .selected").size()+$("#services .service-icon").size();$("#add-services .selected").each(function(){var id=$(this).attr("id");id=id.split("at_avail_");createIcon(id[1],true,"services");});$("#add-services .selected").remove();var availSlots=$("#services .service-icon").size();while(availSlots>11){var removed=$("#services .service-icon:last");removed.remove();$("#add-services").append(removed);availSlots--;}
$(".ui-droppable").sortable({connectWith:'.ui-droppable',cursor:'pointer',cursorAt:false,placeholder:'service-icon-empty',forcePlaceholderSize:true,tolerance:'pointer'});sortServices();});$("#removeServiceBtn").click(function(){$("#services .selected").each(function(){id=$(this).attr("id");});var removed=$("#services .selected");removed.appendTo($("#add-services"));removed.removeClass("selected");$("#services .selected").remove();sortServices();});$("#upBtn").click(function(){var e=$("#services .selected");if(e.prev().attr("title")!==undefined)
e.swapWith(e.prev());});$("#downBtn").click(function(){var e=$("#services .selected");if(typeof e.next().attr("title")!="undefined")
e.swapWith(e.next());});$("#services").droppable({accept:'.add-service-item',tolerance:'pointer',drop:function(evt,ui){$service=ui.draggable;var serviceId=$item.attr("id");$(this).removeClass("service-bg");$("#"+serviceId).remove();$(ui.helper).remove();$("#services .service-icon:last").remove();createIcon(serviceId,true,"add-services");},over:function(evt,ui){$item=ui.draggable;$(this).addClass("service-bg");},out:function(evt,ui){$item=ui.draggable;$(this).removeClass("service-bg");}});});function createIcon(service,drop,div,service_title,service_api){var serviceTitle="",at_service_name="";addThisLoaded=false;if(typeof service_api!="undefined"){var at_service_name=service+"_name";localStorage[at_service_name]=service_title;}
switch(service){case'facebook_like':serviceTitle="Facebook Like";break;case'google_plusone':serviceTitle='Google +1';break;default:at_service_name=service+"_name";serviceTitle=localStorage[at_service_name];break;}
var iconWrap=$('<div class="service-icon ui-sortable" id="at_avail_'+service+'" title="'+service+'" ><div class="addthis_service_icon icon_'+service+'">'+serviceTitle+'</div></div>');drop==true?iconWrap.hide().prependTo('#'+div).fadeIn("slow"):iconWrap.hide().appendTo('#'+div).fadeIn("slow");}
function findService(item){var idx=-1;var arr=new Array();if(localStorage["addthis_sshp"]!=undefined&&localStorage["addthis_sshp"])
arr=localStorage["addthis_sshp"].split(',');for(var i=0;i<arr.length;i++){idx=(item==arr[i])?i:-1;if(-1!=idx)break;}
return idx;}
function sortServices(){$("#add-services > div").css('display','block');$("#add-services > div").tsort("",{attr:"id"});$("#add-services .service-icon").tsort("span");}
function toggleSelected(e){var p=e.parent().attr("id");if(!isCtrl){$("#"+p+" .service-icon").removeClass("selected");e.addClass("selected");}else if(e.hasClass("selected")&&isCtrl){e.removeClass("selected");}else{e.addClass("selected");}}
function iconDoubleClick(e){var p=e.parent().attr("id");var parent=e.parent().attr("class");$("#"+p+" .service-icon").removeClass("selected");e.addClass("selected");if(parent=="null"||parent=="")
{$("#addServiceBtn").click();}
else{$("#removeServiceBtn").click();}}
function makeSortable(){$("#services").sortable({cursor:"move",containment:"parent",opacity:".7",placeholder:"service-icon-empty",change:function(e,ui){ui.item.toggleClass("selected");},update:function(e,ui){}});}
function displayResponse(response){$(function(){var servicesDirty=response.data;var servicesClean=[];for(var i in servicesDirty){var service=servicesDirty[i];if(typeof service=="object"&&ATX.services.blacklist.indexOf(service.code)==-1&&typeof service.code!="undefined"){servicesClean.push(service);}}
appendServices(servicesClean);});}
function appendServices(services){var i=0,mod=10,sleep=100,at_service_name="",tmp_service_title,service_els=$('#add-services');var prefServices=new Array();var tmpTitle=new Array();while(services.length){var service=services.shift();if(servicesExclude.indexOf(service.code)<0){var found=findService(service.code);if(found==-1){createIcon(service.code,false,"add-services",service.name,"append_services");}
tmp_service_title=service.code+"_title";tmpTitle[tmp_service_title]=service.name;}}
if(localStorage["addthis_sshp"]!=undefined&&localStorage["addthis_sshp"])
prefServices=localStorage["addthis_sshp"].split(',');for(var i=0;i<prefServices.length;i++){if(prefServices[i]){tmp_service_title=prefServices[i]+"_title";createIcon(prefServices[i],false,"services",tmpTitle[tmp_service_title],"append_services");}}}
function updateSSH(){var s=[];$("#services .service-icon").each(function(){s.push($(this).attr("title"));});localStorage["addthis_sshp"]=s;}
function updateContextMenuSettings(){if($('#chkContextMenu').attr('checked')){localStorage["context_menu"]=true;bgpage.Preferences.setContextMenu(true);}else{localStorage["context_menu"]=false;bgpage.Preferences.setContextMenu(false);}
if($('#chkContextMenuSearch').attr('checked')){localStorage["context_menu_search"]="true";}else{localStorage["context_menu_search"]="false";}
bgpage.ATX.contextMenu.initialize();}
function setButtonCSS(btnID,text,classConfig){$("#"+btnID)[0].textContent=text;$("#"+btnID).removeClass(classConfig.remove);$("#"+btnID).addClass(classConfig.add);if(text=="Disconnect")
setUserInfo(btnID);}
function setUserInfo(btnID){if(btnID=="btnOAuthFacebook"){$("#divFBUserInfo").css("display","block");$("#imgFBAvatar").removeAttr("src").attr("src",bgpage.FBHandler.avatarImageUrl);$("#spnFBUsername").html(bgpage.FBHandler.screenName);}else if(btnID=="btnOAuthTwitter"){$('#btnOAuthTwitter').attr("disabled",false);$("#divTwitterUserInfo").css("display","block");$("#imgTwitterAvatar").removeAttr("src").attr("src",bgpage.TwitterHandler.avatarImageUrl);$("#spnTwitterUsername").html(bgpage.TwitterHandler.screenName);}}
function disableButton(btnID){$("#"+btnID).attr('disabled','disabled');}
function toggleAuthServices(service,dirCall){if(service=="facebook"){if($("#chkFBAuth").attr("checked")=='checked'){$("#divAuthFB").css("opacity","1");$('#divAuthFB :button').removeAttr('disabled');$('#divAuthFB :button').css("cursor","pointer");$("#chkSocialServices").attr("checked",true);bgpage.Preferences.setFBAuthPreference(true);}else{$("#divAuthFB").css("opacity","0.5");$('#divAuthFB :button').attr('disabled',true);$('#divAuthFB :button').css("cursor","default");bgpage.Preferences.setFBAuthPreference(false);}}else if(service=="twitter"){if($("#chkTwitterAuth").attr("checked")=='checked'){$("#divAuthTwitter").css("opacity","1");$('#divAuthTwitter :button').removeAttr('disabled');$('#divAuthTwitter :button').css("cursor","pointer");$("#chkSocialServices").attr("checked",true);bgpage.Preferences.setTwitterAuthPreference(true);}else{$("#divAuthTwitter").css("opacity","0.5");$('#divAuthTwitter :button').attr('disabled',true);$('#divAuthTwitter :button').css("cursor","default");bgpage.Preferences.setTwitterAuthPreference(false);}}
if($("#chkTwitterAuth").attr("checked")!=='checked'&&$("#chkFBAuth").attr("checked")!=='checked')
$("#chkSocialServices").attr("checked",false);if(dirCall)
toggleSocialServices(true);}
function toggleSocialServices(load){if($("#chkSocialServices").attr("checked")==='checked'){$("#divSocial").css("opacity","1");$('#divSocial :button').removeAttr('disabled');$('#divSocial :button').css("cursor","pointer");localStorage["social_services"]="true";if(!load){$("#chkFBAuth").attr("checked",true);$("#chkTwitterAuth").attr("checked",true);}
bgpage.Preferences.setSocialServices(true);}else{$('#divSocial :button').attr('disabled',true);$("#divSocial").css("opacity",".5");$('#divSocial :button').css("cursor","default");localStorage["social_services"]="false";$("#chkFBAuth").attr("checked",false);$("#chkTwitterAuth").attr("checked",false);bgpage.Preferences.setSocialServices(false);}
toggleAuthServices("facebook",false);toggleAuthServices("twitter",false);}
function showErrorMessage(error){if(error=="Error Timestamp"){if($("#divError").css("display")=="none"){$("#divError").html("Check your system date");$("#divError").fadeIn("fast");setTimeout("showErrorMessage('Error Timestamp')",7000);}else{$("#divError").fadeOut("fast");}}}
$(document).ready(function(){$('#chkSocialServices').change(function(){toggleSocialServices(false);});$('#chkFBAuth').change(function(){toggleAuthServices('facebook',true);});$('#chkTwitterAuth').change(function(){toggleAuthServices('twitter',true);});$('#chkContextMenu').change(function(){updateContextMenuSettings();});$('#chkContextMenuSearch').change(function(){updateContextMenuSettings();});$('[id^=at_avail_]').live('click',function(){toggleSelected($(this));return false;});});