try{
var h,ba=ba||{},l=this,ca="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
l.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"}, quasar_sign_in:{message:"Sign in"}};

}catch(e){_DumpException(e)}
try{
var p=function(a){return void 0!==a},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;
a.q=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Gd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(ma,Error);ma.prototype.name="CustomError";
var pa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",n=e[g]||"",A=RegExp("(\\d*)(\\D*)","g"),J=RegExp("(\\d*)(\\D*)","g");do{var aa=A.exec(k)||["","",""],K=J.exec(n)||["","",""];if(0==aa[0].length&&0==K[0].length)break;c=oa(0==aa[1].length?0:parseInt(aa[1],10),0==K[1].length?0:parseInt(K[1],10))||oa(0==aa[2].length,0==K[2].length)||oa(aa[2], K[2])}while(0==c)}return c},oa=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,qa=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var n=g[k];b.call(c,n,k,a)&&(e[f++]=n)}return e},ta=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,
f[g],g,a));return e},ua=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,g){e=b.call(d,e,c,g,a)});return e},va=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},wa=function(a,b){var c=qa(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var xa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var ya=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},za=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.I=b;t:{if(a.I.length&&(b=a.I.length-1,(c=a.I[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.e=b-a.b;a.c=c;break t}a.e=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.e?(c+=a.b,a.I[c]=a.I[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.e?a.I[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.I.toString()};var B=function(a,b){Ba[a]=b;b.Nb=a},Ba={};
var Ca="StopIteration"in l?l.StopIteration:Error("f"),Da=function(){};Da.prototype.next=function(){throw Ca;};Da.prototype.ia=function(){return this};var Ea;t:{var Fa=l.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){Ea=Ga;break t}}Ea=""}var Ha=function(a){return-1!=Ea.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.e=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.N(),d=a.C()):(c=Aa(a),d=za(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};h=C.prototype;h.X=function(){return this.c};h.C=function(){Ia(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};h.N=function(){Ia(this);return this.b.concat()};h.R=function(){return 0==this.c};
h.clear=function(){this.a={};this.e=this.c=this.b.length=0};h.remove=function(a){return Ja(this.a,a)?(delete this.a[a],this.c--,this.e++,this.b.length>2*this.c&&Ia(this),!0):!1};var Ia=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ja(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ja(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};h=C.prototype;h.get=function(a,b){return Ja(this.a,a)?this.a[a]:b};
h.set=function(a,b){Ja(this.a,a)||(this.c++,this.b.push(a),this.e++);this.a[a]=b};h.forEach=function(a,b){for(var c=this.N(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new C(this)};h.ia=function(a){Ia(this);var b=0,c=this.b,d=this.a,e=this.e,f=this,g=new Da;g.next=function(){for(;;){if(e!=f.e)throw Error("i");if(b>=c.length)throw Ca;var g=c[b++];return a?g:d[g]}};return g};var Ja=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Ka=function(a){if("function"==typeof a.C)return a.C();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return za(a)},La=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.N)d=a.N();else if("function"!=typeof a.C)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Aa(a);else d=void 0;for(var e=Ka(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Ma=Ha("Opera")||Ha("OPR"),D=Ha("Trident")||Ha("MSIE"),Na=Ha("Gecko")&&-1==Ea.toLowerCase().indexOf("webkit")&&!(Ha("Trident")||Ha("MSIE")),Oa=-1!=Ea.toLowerCase().indexOf("webkit"),Pa=l.navigator||null,Qa=Pa&&Pa.platform||"",Ra=function(){var a=l.document;return a?a.documentMode:void 0},Sa=function(){var a="",b;if(Ma&&l.opera)return a=l.opera.version,s(a)?a():a;Na?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Oa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Ea))?a[1]:"");return D&&(b= Ra(),b>parseFloat(a))?String(b):a}(),Ta={},Ua=function(a){return Ta[a]||(Ta[a]=0<=pa(Sa,a))},Va=l.document,Wa=Va&&D?Ra()||("CSS1Compat"==Va.compatMode?parseInt(Sa,10):5):void 0;
var E=function(){};E.prototype.H=!1;E.prototype.Kb=function(){return this.H};E.prototype.D=function(){this.H||(this.H=!0,this.n())};E.prototype.n=function(){if(this.v)for(;this.v.length;)this.v.shift()()};var F=function(a){a&&"function"==typeof a.D&&a.D()};
var Xa=!D||D&&9<=Wa;!Na&&!D||D&&D&&9<=Wa||Na&&Ua("1.9.1");D&&Ua("9");var Ya=function(a){Ya[" "](a);return a};Ya[" "]=ka;var Za=function(a,b){try{return Ya(a[b]),!0}catch(c){}return!1};var $a=!D||D&&9<=Wa,ab=D&&!Ua("9");!Oa||Ua("528");Na&&Ua("1.9b")||D&&Ua("8")||Ma&&Ua("9.5")||Oa&&Ua("528");Na&&!Ua("8")||D&&Ua("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.yc=!0};G.prototype.D=function(){};G.prototype.b=function(){this.yc=!1};var bb=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Na&&Za(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};q(bb,G); bb.prototype.b=function(){bb.q.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ab)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var cb="closure_listenable_"+(1E6*Math.random()|0),eb=function(a){return!(!a||!a[cb])},fb=0;var gb=function(a,b,c,d,e){this.ra=a;this.proxy=null;this.src=b;this.type=c;this.cb=!!d;this.kb=e;this.key=++fb;this.removed=this.bb=!1},hb=function(a){a.removed=!0;a.ra=null;a.proxy=null;a.src=null;a.kb=null};var ib=function(a){this.src=a;this.a={};this.b=0},kb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=jb(b,c,e,f);-1<k?(a=b[k],d||(a.bb=!1)):(a=new gb(c,a.src,g,!!e,f),a.bb=d,b.push(a));return a};ib.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=jb(e,b,c,d);return-1<b?(hb(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var lb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=wa(a.a[c],b);d&&(hb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};ib.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,hb(d[e]);delete this.a[c];this.b--}return b}; var mb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=jb(a,c,d,e));return-1<b?a[b]:null},jb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.ra==b&&f.cb==!!c&&f.kb==d)return e}return-1};
var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0,qb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);return null}c=rb(c);return eb(a)?a.listen(b,c,d,e):sb(a,b,c,!1,d,e)},sb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,k=tb(a);k||(a[nb]=k=new ib(a));c=kb(k,b,c,d,e,f);if(c.proxy)return c;d=ub();c.proxy=d;d.src=a;d.ra=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(vb(b.toString()),d);pb++;return c},ub=function(){var a=wb,b=$a?function(c){return a.call(b.src,
b.ra,c)}:function(c){c=a.call(b.src,b.ra,c);if(!c)return c};return b},xb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);else c=rb(c),eb(a)?a.Tb(b,c,d,e):a&&(a=tb(a))&&(b=mb(a,b,c,!!d,e))&&yb(b)},yb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(eb(b))return lb(b.W,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.cb):b.detachEvent&&b.detachEvent(vb(c),d);pb--;(c=tb(b))?(lb(c,a),0==c.b&&(c.src=null,b[nb]=null)):hb(a);return!0},vb=function(a){return a in
ob?ob[a]:ob[a]="on"+a},Ab=function(a,b,c,d){var e=1;if(a=tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.cb==c&&!f.removed&&(e&=!1!==zb(f,d))}return Boolean(e)},zb=function(a,b){var c=a.ra,d=a.kb||a.src;a.bb&&yb(a);return c.call(d,b)},wb=function(a,b){if(a.removed)return!0;if(!$a){var c;if(!(c=b))t:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new bb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;0<=k;k--)c.a=e[k],d&=Ab(e[k],f,!0,c);for(k=0;k<e.length;k++)c.a=e[k],d&=Ab(e[k],f,!1,c)}return d}return zb(a,new bb(b,this))},tb=function(a){a=a[nb];return a instanceof ib?a:null},Bb="__closure_events_fn_"+(1E9*Math.random()>>>0),rb=function(a){return s(a)?a:a[Bb]||(a[Bb]=function(b){return a.handleEvent(b)})};
var Cb=function(a){y(this,a,"h_cc",[])};q(Cb,x);B("h_cc",Cb);Cb.prototype.Z=function(){return z(this,19)};var H=function(a){this.L=a;this.h={}};q(H,E);var Db=[];H.prototype.listen=function(a,b,c,d){return Eb(this,a,b,c,d)};var Eb=function(a,b,c,d,e,f){u(c)||(c&&(Db[0]=c.toString()),c=Db);for(var g=0;g<c.length;g++){var k=qb(b,c[g],d||a.handleEvent,e||!1,f||a.L||a);if(!k)break;a.h[k.key]=k}return a};
H.prototype.Tb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Tb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.L||this,c=rb(c),d=!!d,b=eb(a)?mb(a.W,String(b),c,d,e):a?(a=tb(a))?mb(a,b,c,d,e):null:null,b&&(yb(b),delete this.h[b.key]);return this};H.prototype.removeAll=function(){ya(this.h,yb);this.h={}};H.prototype.n=function(){H.q.n.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){this.W=new ib(this);this.O=this;this.w=null};q(I,E);I.prototype[cb]=!0;h=I.prototype;h.addEventListener=function(a,b,c,d){qb(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){xb(this,a,b,c,d)};h.n=function(){I.q.n.call(this);this.W&&this.W.removeAll(void 0);this.w=null};h.listen=function(a,b,c,d){return kb(this.W,String(a),b,!1,c,d)};h.Tb=function(a,b,c,d){return this.W.remove(String(a),b,c,d)}; h.ea=function(a,b,c){a=this.W.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.cb==b){var g=f.ra,k=f.kb||f.src;f.bb&&lb(this.W,f);d=!1!==g.call(k,c)&&d}}return d&&!1!=c.yc};
var Fb,Gb,Hb,Ib,Jb,Kb,Lb;Lb=Kb=Jb=Ib=Hb=Gb=Fb=!1;var Mb=Ea;Mb&&(-1!=Mb.indexOf("Firefox")?Fb=!0:-1!=Mb.indexOf("Camino")?Gb=!0:-1!=Mb.indexOf("iPhone")||-1!=Mb.indexOf("iPod")?Hb=!0:-1!=Mb.indexOf("iPad")?Ib=!0:-1!=Mb.indexOf("Chrome")?Kb=!0:-1!=Mb.indexOf("Android")?Jb=!0:-1!=Mb.indexOf("Safari")&&(Lb=!0));var Ob=Fb,Pb=Gb,Qb=Hb,Rb=Ib,Sb=Jb,Tb=Kb,Ub=Lb;
var L=function(a){this.a=a};L.prototype.toString=function(){return this.a};var Vb=new L("b"),Wb=new L("c"),Xb=new L("h"),Yb=new L("k"),Zb=new L("G"),$b=new L("M"),ac=new L("N");var bc=new L("ea");var dc=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("o");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,A,J,aa){if("%"==A)return"%";var K=c.shift();if("undefined"==typeof K)throw Error("p");arguments[0]=K;return cc[A].apply(null,arguments)})},cc={s:function(a,b,c){return isNaN(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+Array(c-a.length+1).join(" "):Array(c-a.length+1).join(" ")+a},f:function(a,b,c,
d,e){d=a.toString();isNaN(e)||""==e||(d=a.toFixed(e));var f;f=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=f+d);if(isNaN(c)||d.length>=c)return d;d=isNaN(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=c-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Array(a+1).join(" "):f+Array(a+1).join(0<=b.indexOf("0",0)?"0":" ")+d},d:function(a,b,c,d,e,f,g,k){return cc.f(parseInt(a,10),b,c,d,0,f,g,k)}};cc.i=cc.d;cc.u=cc.d;
var ec=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},M=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=dc("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+dc(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+dc.apply({},c)))},fc=function(){return 0<=navigator.userAgent.indexOf("CrOS")};
var gc=function(a,b){this.e=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.g=null;this.j=b||"u";this.a=this.v=null;this.h=[]};gc.prototype.message=function(){var a={};a.i=this.a;a.m=this.h;a.r=this.j;a.o=this.v;a.s=this.b;a.st=this.c;a.d=this.g;a.dt=this.e;return a};ga("ace.base.Message.prototype.message",gc.prototype.message);
var hc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.a=b[c];break;case "m":a.h=b[c];break;case "o":a.v=b[c];break;case "s":a.b=b[c];break;case "d":a.g=b[c];break;case "st":a.c=b[c];break;case "dt":a.e=b[c]}return a},ic=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))},jc=function(a,b){null!=b&&(a.a=b)},kc=function(a,b){"object"==typeof b?a.h=b:a.h=[b]};gc.prototype.source=function(){return this.b};gc.prototype.target=function(){return this.g};gc.prototype.Ac=function(){return this.c}; gc.prototype.content=function(){return this.h};
var lc=function(a,b,c,d,e){this.b=a;this.Ua=b;this.a=typeof b;this.Ob=c?c:!1;this.ca=!0;this.Ib=d?d:!1;this.Bb=e?e:!1};q(lc,E);h=lc.prototype;h.n=function(){lc.q.n.call(this);this.b="";this.Ua=null;this.a=""};h.id=function(){return this.b};h.type=function(){return this.a};h.G=function(){return this.Ua};h.setEnabled=function(a){this.ca=a};
var mc=function(a){return(a=a.exec(Ea))?a[1]:""},nc=function(){if(Ob)return mc(/Firefox\/([0-9.]+)/);if(D||Ma)return Sa;if(Tb)return mc(/Chrome\/([0-9.]+)/);if(Ub)return mc(/Version\/([0-9.]+)/);if(Qb||Rb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ea))return a[1]+"."+a[2]}else{if(Sb)return(a=mc(/Android\s+([0-9.]+)/))?a:mc(/Version\/([0-9.]+)/);if(Pb)return mc(/Camino\/([0-9.]+)/)}return""}();
var pc=function(a){this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&oc(this,a)};q(pc,E);var qc=0<=pa(nc,"23.0.1262.0")&&!fc();pc.prototype.n=function(){pc.q.n.call(this);for(var a=this.a.N(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};pc.prototype.getItem=function(a){return Ja(this.a.a,a)?this.a.get(a):null};pc.prototype.setItem=function(a){this.a.set(a.id(),a)}; var oc=function(a,b){for(var c in b){var d=b[c],e=null;Ja(a.a.a,c)?(e=a.a.get(c),e.Ua=d.value,d.changed&&(e.Bb=d.changed)):(e=new lc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var rc=function(a){l.setTimeout(function(){throw a;},0)},uc=function(a,b){var c=a;b&&(c=r(a,b));s(l.setImmediate)?l.setImmediate(c):(sc||(sc=tc()),sc(c))},sc,tc=function(){if(l.Promise&&l.Promise.resolve){var a=l.Promise.resolve();return function(b){a.then(function(){try{b()}catch(a){rc(a)}})}}var b=l.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";
document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.ac;d.ac=null;a()};return function(a){e.next=
{ac:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};
var zc=function(a,b){vc||(uc(wc),vc=!0);xc.push(new yc(a,b))},vc=!1,xc=[],wc=function(){for(;xc.length;){var a=xc;xc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){rc(d)}}}vc=!1},yc=function(a,b){this.a=a;this.b=b};var Ac=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Bc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Dc=function(a,b){this.b=0;this.h=void 0;this.a=this.c=null;this.e=this.g=!1;try{var c=this;a.call(b,function(a){Cc(c,2,a)},function(a){Cc(c,3,a)})}catch(d){Cc(this,3,d)}},Fc=function(){var a,b=new Dc(function(b){a=b});return new Ec(b,a)};Dc.prototype.then=function(a,b,c){return Gc(this,s(a)?a:null,s(b)?b:null,c)};Ac(Dc);
var Jc=function(a){0==a.b&&zc(function(){var a=new Hc(void 0);Ic(this,a)},a)},Ic=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.eb)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?Ic(c,b):(d=c.a.splice(e,1)[0],Kc(c,d,3,b)))}}else Cc(a,3,b)},Mc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||Lc(a);a.a||(a.a=[]);a.a.push(b)},Gc=function(a,b,c,d){var e={eb:null,tc:null,vc:null};e.eb=new Dc(function(a,g){e.tc=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){g(A)}}:
a;e.vc=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof Hc?g(b):a(e)}catch(A){g(A)}}:g});e.eb.c=a;Mc(a,e);return e.eb};Dc.prototype.v=function(a){this.b=0;Cc(this,2,a)};Dc.prototype.j=function(a){this.b=0;Cc(this,3,a)};
var Cc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(Bc(c)){a.b=1;c.then(a.v,a.j,a);return}if(ha(c))try{var d=c.then;if(s(d)){Nc(a,c,d);return}}catch(e){b=3,c=e}}a.h=c;a.b=b;Lc(a);3!=b||c instanceof Hc||Oc(a,c)}},Nc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.v(b))},f=function(b){d||(d=!0,a.j(b))};try{c.call(b,e,f)}catch(g){f(g)}},Lc=function(a){a.g||(a.g=!0,zc(a.k,a))};
Dc.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)Kc(this,a[b],this.b,this.h)}this.g=!1};var Kc=function(a,b,c,d){if(2==c)b.tc(d);else{for(;a&&a.e;a=a.c)a.e=!1;b.vc(d)}},Oc=function(a,b){a.e=!0;zc(function(){a.e&&Pc.call(null,b)})},Pc=rc,Hc=function(a){ma.call(this,a)};q(Hc,ma);Hc.prototype.name="cancel";var Ec=function(a,b){this.b=a;this.a=b};
var Sc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Qc;this.b=!0;Rc(this)};Sc.wa=function(){return Sc.a?Sc.a:Sc.a=new Sc};var Rc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){var b=chrome.runtime?chrome.runtime.lastError:void 0;b&&M("chrome storage read error "+b);if(!this.b){for(var f in a)this.c.set(f,a[f]);this.b=!0}c()},a))};Sc.prototype.get=function(a){return this.a.get(a)};Sc.prototype.set=function(a,b){var c=Fc();this.a.set(a,b);c.a(void 0);return c.b};
Sc.prototype.remove=function(a){this.a.remove(a)};Sc.prototype.clear=function(){this.a.clear()};var Qc=function(){this.a=window.localStorage};Qc.prototype.clear=function(){this.a.clear()};Qc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ba[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a}; Qc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.I,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Qc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Tc=function(a,b){this.b=a;this.a=b;this.constructor.Zb||(this.constructor.Zb={});this.constructor.Zb[this.toString()]=this};Tc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var N=function(a,b){Tc.call(this,a,b)};q(N,Tc);var Uc=function(a){this.a=a},Vc=new Uc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Wc=function(a,b){this.e=[];this.w=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.h=!1;this.g=0;this.j=null;this.t=0};Wc.prototype.k=function(a,b){this.h=!1;Xc(this,a,b)};var Xc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Yc(a)},$c=function(a){if(a.a){if(!a.l)throw new Zc;a.l=!1}};Wc.prototype.v=function(a){$c(this);Xc(this,!0,a)};var ad=function(a,b,c,d){a.e.push([b,c,d]);a.a&&Yc(a)};
Wc.prototype.then=function(a,b,c){var d,e,f=new Dc(function(a,b){d=a;e=b});ad(this,d,function(a){"undefined"!=typeof bd&&a instanceof bd?Jc(f):e(a)});return f.then(a,b,c)};Ac(Wc);
var cd=function(a){return va(a.e,function(a){return s(a[1])})},Yc=function(a){if(a.g&&a.a&&cd(a)){var b=a.g,c=dd[b];c&&(l.clearTimeout(c.gb),delete dd[b]);a.g=0}a.j&&(a.j.t--,delete a.j);for(var b=a.c,d=c=!1;a.e.length&&!a.h;){var e=a.e.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var k=f.call(e||a.w,b);p(k)&&(a.b=a.b&&(k==b||k instanceof Error),a.c=b=k);Bc(b)&&(d=!0,a.h=!0)}catch(n){b=n,a.b=!0,cd(a)||(c=!0)}}a.c=b;d&&(k=r(a.k,a,!0),d=r(a.k,a,!1),b instanceof Wc?(ad(b,k,d),b.p=!0):b.then(k,d));c&&
(b=new ed(b),dd[b.gb]=b,a.g=b.gb)},Zc=function(){ma.call(this)};q(Zc,ma);Zc.prototype.message="Deferred has already fired";Zc.prototype.name="AlreadyCalledError";var ed=function(a){this.gb=l.setTimeout(r(this.b,this),0);this.a=a};ed.prototype.b=function(){delete dd[this.gb];throw this.a;};var dd={};

}catch(e){_DumpException(e)}
try{
var fd=function(){return chrome.runtime.getURL("feedbackdialog.html")},gd=function(a,b){for(var c=t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};var id=function(a){this.c={};this.j={};this.k={};this.e={};this.l={};this.t={};this.p=a?a.va():new I;this.B=!a;this.g=null;a?(this.g=a,this.k=a.k,this.e=a.e,this.j=a.j,this.l=a.l):m();a=hd(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};q(id,E);var hd=function(a){for(;a.g;)a=a.g;return a};id.prototype.get=function(a){var b=this.b(a);if(null==b)throw new jd(a);return b};
id.prototype.b=function(a){for(var b=this;b;b=b.g){if(b.H)throw Error("q");if(b.c[a])return b.c[a][0];if(b.t[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};id.prototype.a=function(a,b,c){if(this.H)c||F(b);else{this.c[a]=[b,!c];b=kd(this,this,a);for(c=0;c<b.length;c++)b[c].v(null);delete this.j[a]}};id.prototype.w=function(){var a=ld;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&F(b[0])};
var kd=function(a,b,c){var d=[],e=a.e[c];e&&(gd(e,function(a){var c;t:{for(c=a.$b;c;){if(c==b){c=!0;break t}c=c.g}c=!1}c&&(d.push(a.Hd),wa(e,a))}),0==e.length&&delete a.e[c]);return d},md=function(a,b){a.e&&La(a.e,function(a,d,e){gd(a,function(d){d.$b==b&&wa(a,d)});0==a.length&&delete e[d]})};
id.prototype.n=function(){if(hd(this)==this){var a=this.h;if(a)for(;a.length;)a[0].D()}else for(var a=hd(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].D&&a[0].D();this.c=null;this.B&&this.p.D();md(this,this);this.e=null;F(this.A);this.t=this.A=null;id.q.n.call(this)};id.prototype.va=function(){return this.p};var jd=function(a){ma.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};q(jd,ma); var nd=new Uc("fva");new N(nd,1);

}catch(e){_DumpException(e)}
try{
var od={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pd=function(a,b){b.push('"',a.replace(xa,function(a){if(a in od)return od[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return od[a]=e+b.toString(16)}),'"')},qd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),rd=function(a,b,c){switch(typeof b){case "string":pd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),rd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),pd(e,c),c.push(":"),rd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}},sd=function(){},td=function(a,
b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)td(a,b[f],c,d,e);return null}c=rb(c);return eb(a)?kb(a.W,String(b),c,!0,d,e):sb(a,b,c,!0,d,e)},ud=Oa,vd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,O=function(a,b,c){b<a.e?a.I[b+a.b]=c:a.c[b]=c},wd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<qd.length;f++)c=qd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},xd=function(a){var b=
[];rd(new sd,a,b);return b.join("")},yd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},zd=function(a){a=a.b[0];M("getApplicationPath: "+a);return a},Ad=function(a,b,c){null!=b&&(a.g=b,null!=c&&(a.e=c))},P=function(a,b){var c,d=a.w;if(d)for(c=[];d;d=d.w)c.push(d);var d=a.O,e=b,f=e.type||e;if(t(e))e=new G(e,d);else if(e instanceof G)e.target=e.target||d;else{var g=e,e=new G(f,d);wd(e,g)}var g=!0,k;if(c)for(var n=
c.length-1;0<=n;n--)k=e.a=c[n],g=k.ea(f,!0,e)&&g;k=e.a=d;g=k.ea(f,!0,e)&&g;g=k.ea(f,!1,e)&&g;if(c)for(n=0;n<c.length;n++)k=e.a=c[n],g=k.ea(f,!1,e)&&g},Bd=function(a,b,c,d,e,f){if(u(c))for(var g=0;g<c.length;g++)Bd(a,b,c[g],d,e,f);else{b=td(b,c,d||a.handleEvent,e,f||a.L||a);if(!b)return a;a.h[b.key]=b}return a},Cd=function(a){if(ud){ud=!1;var b=l.location;if(b){var c=b.href;if(c&&(c=(c=Cd(c)[3]||null)&&decodeURIComponent(c))&&c!=b.hostname)throw ud=!0,Error();}}return a.match(vd)},Q=function(a,b){var c=
yd(F,b);a.v||(a.v=[]);a.v.push(p(void 0)?r(c,void 0):c)},Dd=function(a,b,c){var d=c?c.I:c;a.a[b]=c;O(a,b,d)},Ed=function(a,b,c){if(!a.a[c]){var d=z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Fd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Gd=function(a){return a?decodeURIComponent(a):""},Hd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Id=function(a){return v.concat.apply(v,arguments)},Jd=function(a,b,c){this.a=
a||null;this.b=!!c},Md=function(a){if(!a.J&&(a.J=new C,a.Q=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Ld(a,e);d=a;f=f?decodeURIComponent(f.replace(/\+/g," ")):"";Md(d);d.a=null;var e=Ld(d,e),g=d.J.get(e);g||d.J.set(e,g=[]);g.push(f);d.Q++}};h=Jd.prototype;h.J=null;h.Q=null;h.X=function(){Md(this);return this.Q};
h.remove=function(a){Md(this);a=Ld(this,a);return Ja(this.J.a,a)?(this.a=null,this.Q-=this.J.get(a).length,this.J.remove(a)):!1};h.clear=function(){this.J=this.a=null;this.Q=0};h.R=function(){Md(this);return 0==this.Q};var Nd=function(a,b){Md(a);b=Ld(a,b);return Ja(a.J.a,b)};Jd.prototype.N=function(){Md(this);for(var a=this.J.C(),b=this.J.N(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Jd.prototype.C=function(a){Md(this);var b=[];if(t(a))Nd(this,a)&&(b=Id(b,this.J.get(Ld(this,a))));else{a=this.J.C();for(var c=0;c<a.length;c++)b=Id(b,a[c])}return b};Jd.prototype.set=function(a,b){Md(this);this.a=null;a=Ld(this,a);Nd(this,a)&&(this.Q-=this.J.get(a).length);this.J.set(a,[b]);this.Q++;return this};Jd.prototype.get=function(a,b){var c=a?this.C(a):[];return 0<c.length?String(c[0]):b};var Od=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.J.set(Ld(a,b),Hd(c)),a.Q+=c.length)};
Jd.prototype.toString=function(){if(this.a)return this.a;if(!this.J)return"";for(var a=[],b=this.J.N(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.C(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.a=a.join("&")};Jd.prototype.clone=function(){var a=new Jd;a.a=this.a;this.J&&(a.J=this.J.clone(),a.Q=this.Q);return a};
var Ld=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c},Pd=function(a,b){b&&!a.b&&(Md(a),a.a=null,a.J.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Od(this,e,a))},a));a.b=b},Qd=/#/g,Rd=/[\#\?@]/g,Sd=/[\#\?]/g,Td=/[\#\?:]/g,Ud=/[#\/\?@]/g,Vd=function(a,b){return t(a)?encodeURI(a).replace(b,Fd):null},Wd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^m()).toString(36)},Xd=function(a,b){var c;"undefined"!=
typeof Xd&&a instanceof Xd?(this.oa=p(b)?b:a.oa,Yd(this,a.ga),this.ta=a.ta,this.U=a.U,Zd(this,a.fa),this.P=a.P,$d(this,a.a.clone()),this.na=a.na):a&&(c=Cd(String(a)))?(this.oa=!!b,Yd(this,c[1]||"",!0),this.ta=Gd(c[2]||""),this.U=Gd(c[3]||""),Zd(this,c[4]),this.P=Gd(c[5]||""),$d(this,c[6]||"",!0),this.na=Gd(c[7]||"")):(this.oa=!!b,this.a=new Jd(null,0,this.oa))};h=Xd.prototype;h.ga="";h.ta="";h.U="";h.fa=null;h.P="";h.na="";h.oa=!1;
h.toString=function(){var a=[],b=this.ga;b&&a.push(Vd(b,Ud),":");if(b=this.U){a.push("//");var c=this.ta;c&&a.push(Vd(c,Ud),"@");a.push(encodeURIComponent(String(b)));b=this.fa;null!=b&&a.push(":",String(b))}if(b=this.P)this.U&&"/"!=b.charAt(0)&&a.push("/"),a.push(Vd(b,"/"==b.charAt(0)?Sd:Td));(b=this.a.toString())&&a.push("?",b);(b=this.na)&&a.push("#",Vd(b,Qd));return a.join("")};
var ae=function(a,b){var c=a.clone(),d=!!b.ga;d?Yd(c,b.ga):d=!!b.ta;d?c.ta=b.ta:d=!!b.U;d?c.U=b.U:d=null!=b.fa;var e=b.P;if(d)Zd(c,b.fa);else if(d=!!b.P){if("/"!=e.charAt(0))if(a.U&&!a.P)e="/"+e;else{var f=c.P.lastIndexOf("/");-1!=f&&(e=c.P.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],k=0;k<f.length;){var n=f[k++];"."==n?e&&k==f.length&&g.push(""):".."==n?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),
e&&k==f.length&&g.push("")):(g.push(n),e=!0)}e=g.join("/")}else e=f}d?c.P=e:d=""!==b.a.toString();d?$d(c,Gd(b.a.toString())):d=!!b.na;d&&(c.na=b.na);return c};Xd.prototype.clone=function(){return new Xd(this)};
var Yd=function(a,b,c){a.ga=c?Gd(b):b;a.ga&&(a.ga=a.ga.replace(/:$/,""))},Zd=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("j`"+b);a.fa=b}else a.fa=null},$d=function(a,b,c){b instanceof Jd?(a.a=b,Pd(a.a,a.oa)):(c||(b=Vd(b,Rd)),a.a=new Jd(b,0,a.oa))},R=function(a,b,c){a.a.set(b,c)},be=function(a,b,c){u(c)||(c=[String(c)]);Od(a.a,b,c)},ce=function(a,b){return a.a.get(b)},de=function(a,b,c){return 2>=arguments.length?v.slice.call(a,b):v.slice.call(a,b,c)},ee=function(a,b){return 0<=qa(a,
b)},fe=function(a,b,c){if(s(a))c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=r(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:l.setTimeout(a,b||0)},ge=function(a){l.clearTimeout(a)},he=function(a){var b={},c;for(c in a)b[c]=a[c];return b},ie=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,k=0;k<g;k++)a[f+k]=d[k];else a.push(d)}}, je=function(a,b){var c;t:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]};
var ke=function(){},ne=function(a){var b=a.ka,c=function(a){c.q.constructor.call(this,a);var b=this.V.length;this.a=[];for(var d=0;d<b;++d)this.V[d].Jd||(this.a[d]=new this.V[d](a))};q(c,b);for(var d=[];a;){if(b=a.ka){b.V&&ie(d,b.V);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&s(b[e])&&b[e]!==a){var f=!!b[e].Uc,g=le(e,b,d,f);(f=me(e,b,g,f))&&(c.prototype[e]=f)}}a=a.q&&a.q.constructor}c.prototype.V=d;return c},le=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),
!d));++f);return e},me=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.V[c[0]].prototype[a].apply(this,arguments)}:b[a].Wc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=this.a[c[e]];if(n=n?n[a].apply(n,d):this.V[c[e]].prototype[a].apply(this,d)){d=n;break t}}d=!1}return d}:b[a].Vc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=
this.a[c[e]],n=n?n[a].apply(n,d):this.V[c[e]].prototype[a].apply(this,d);if(null!=n){d=n;break t}}d=void 0}return d}:b[a].rc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var n=this.a[c[e]];n?n[a].apply(n,d):this.V[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],n=0;n<c.length;++n){var A=this.a[c[n]];e.push(A?A[a].apply(A,d):this.V[c[n]].prototype[a].apply(this,d))}return e}:d||b[a].Wc||b[a].Vc||b[a].rc? e=null:e=oe;return e},oe=function(){return[]};ke.prototype.Fb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var qe=function(a){if(!a.Cb){var b;for(b=a.constructor;b&&!b.ka;)b=b.q&&b.q.constructor;b.ka.dc||(b.ka.dc=ne(b));b=new b.ka.dc(a);a.Cb=b;a.Fb||(a.Fb=pe)}},pe=function(a){return this.Cb.Fb(a)};var re=function(){};re.prototype.a=null;var te=function(a){var b;(b=a.a)||(b={},se(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var ue,ve=function(){};q(ve,re);var we=function(a){return(a=se(a))?new ActiveXObject(a):new XMLHttpRequest},se=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("v");}return a.b};ue=new ve;
var xe=function(a){I.call(this);this.F=new C;this.k=a||null;this.b=!1;this.j=this.a=null;this.t="";this.e=0;this.c=this.p=this.g=this.l=!1;this.A=0;this.h=null;this.L="";this.B=this.ba=!1};q(xe,I);var ye=/^https?$/i,ze=["POST","PUT"],Ae=[];xe.prototype.S=function(){this.D();wa(Ae,this)};
xe.prototype.send=function(a,b,c,d){if(this.a)throw Error("w`"+this.t+"`"+a);b=b?b.toUpperCase():"GET";this.t=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?we(this.k):we(ue);this.j=this.k?te(this.k):te(ue);this.a.onreadystatechange=r(this.K,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Be(this);return}a=c||"";var f=this.F.clone();d&&La(d,function(a,b){f.set(b,a)});d=je(f.N(),Ce);c=l.FormData&&a instanceof l.FormData;!ee(ze,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.L&&(this.a.responseType=this.L);"withCredentials"in this.a&&(this.a.withCredentials=this.ba);try{De(this),0<this.A&&((this.B=Ee(this.a))?(this.a.timeout=this.A,this.a.ontimeout=r(this.M,this)):this.h=fe(this.M,this.A,this)),this.g=!0,this.a.send(a),this.g=!1}catch(g){Be(this)}};var Ee=function(a){return D&&Ua(9)&&ia(a.timeout)&&p(a.ontimeout)},Ce=function(a){return"content-type"==a.toLowerCase()};
xe.prototype.M=function(){"undefined"!=typeof ba&&this.a&&(this.e=8,P(this,"timeout"),Fe(this,8))};var Be=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Ge(a);He(a)},Ge=function(a){a.l||(a.l=!0,P(a,"complete"),P(a,"error"))},Fe=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,P(a,"complete"),P(a,"abort"),He(a))};xe.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),He(this,!0));xe.q.n.call(this)};
xe.prototype.K=function(){this.H||(this.p||this.g||this.c?Ie(this):this.aa())};xe.prototype.aa=function(){Ie(this)};
var Ie=function(a){if(a.b&&"undefined"!=typeof ba&&(!a.j[1]||4!=(a.a?a.a.readyState:0)||2!=Je(a)))if(a.g&&4==(a.a?a.a.readyState:0))fe(a.K,0,a);else if(P(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Ke(a)?(P(a,"complete"),P(a,"success")):(a.e=6,Ge(a))}finally{He(a)}}},He=function(a,b){if(a.a){De(a);var c=a.a,d=a.j[0]?ka:null;a.a=null;a.j=null;b||P(a,"ready");try{c.onreadystatechange=d}catch(e){}}},De=function(a){a.a&&a.B&&(a.a.ontimeout=null);ia(a.h)&&(ge(a.h),a.h=null)},Ke=function(a){var b=
Je(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=Cd(String(a.t))[1]||null,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!ye.test(a?a.toLowerCase():"");c=b}return c},Je=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},Le=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
var Me=function(a){y(this,a,"h_cs",[])};q(Me,x);B("h_cs",Me);var Ne=new L("HwdKC");
}catch(e){_DumpException(e)}
try{
var Oe=function(a){return a instanceof Xd?a.clone():new Xd(a,void 0)},Pe=function(a){y(this,a,0,[])};q(Pe,x);var Qe=function(a){y(this,a,0,[])};q(Qe,x);var Re=function(a){y(this,a,0,[])};q(Re,x);
var Se=/[?&]($|#)/,Te=/#|$/,Ue=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},Ve=function(a){if(a&&"number"==typeof a.length){if(ha(a))return"function"==typeof a.item||"string"==typeof a.item;if(s(a))return"function"==typeof a.item}return!1},We={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Xe=/[\x00&<>"']/,Ye=/\x00/g,Ze=/'/g,$e=/"/g,af=/>/g,bf=/</g,cf=/&/g,df=function(a,b,c){function d(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ja(f)||ha(f)&&0<f.nodeType?d(f):w(Ve(f)?Hd(f):f,d)}},ef=function(a,b){ya(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in We?a.setAttribute(We[d],b):0==d.lastIndexOf("aria-",0)||0==
d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},ff=function(a){if(!Xe.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(cf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(bf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(af,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace($e,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ze,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ye,"&#0;"));return a},gf={LOADING:0,Fc:1,Ed:2,Fd:3,ERROR:4,LOADED:5,Ec:6},hf=/\s*;\s*/,jf=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
kf=function(a,b,c){for(var d=a.search(Te),e=0,f,g=[];0<=(f=Ue(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=[g.join("").replace(Se,"$1"),"&",b];null!=c&&a.push("=",encodeURIComponent(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},lf=function(a,b){return sa(a,function(a){return!ee(b,a)})},mf=function(a){a=a.className;return t(a)&&
a.match(/\S+/g)||[]},nf=function(a){I.call(this);this.c=a;this.a=gf.LOADING;this.b=new H(this);Q(this,this.b);this.b.listen(this.c.va(),"h_cs",this.e)};q(nf,I);nf.prototype.e=function(a){a=new Me(a.lb);this.a!=z(a,1)&&(this.a=z(a,1),P(this,"i"))};var of=function(a){this.a=a};h=of.prototype;
h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("t`"+a);if(/[;\r\n]/.test(b))throw Error("u`"+b);p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(m()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(hf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
h.remove=function(a,b,c){var d=p(this.get(a));this.set(a,"",0,b,c);return d};h.N=function(){return pf(this).keys};h.C=function(){return pf(this).Dd};h.R=function(){return!this.a.cookie};h.X=function(){return this.a.cookie?(this.a.cookie||"").split(hf).length:0};h.clear=function(){for(var a=pf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
var pf=function(a){a=(a.a.cookie||"").split(hf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Dd:c}},qf=function(a){(a?a:function(){}).Uc=!0},rf=function(a,b,c){var d=arguments,e=document,f=d[0],g=d[1];if(!Xa&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ff(g.name),'"');if(g.type){f.push(' type="',ff(g.type),'"');var k={};wd(k,g);delete k.type;g=k}f.push(">");f=f.join("")}f=e.createElement(f);
g&&(t(g)?f.className=g:u(g)?f.className=g.join(" "):ef(f,g));2<d.length&&df(e,f,d);return f},sf=function(a){var b=a||document,c=null;if(b.querySelectorAll&&b.querySelector)c=b.querySelector(".talk_loading_msg");else{var d,b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".talk_loading_msg");else if(a.getElementsByClassName){var e=a.getElementsByClassName("talk_loading_msg");a=e}else{e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className;"function"==
typeof f.split&&ee(f.split(/\s+/),"talk_loading_msg")&&(d[c++]=a)}d.length=c;a=d}c=a[0]}return c||null},tf=function(a,b){var c=mf(a),c=lf(c,de(arguments,1));a.className=c.join(" ")},uf=function(a,b){for(var c=mf(a),d=c,e=de(arguments,1),f=0;f<e.length;f++)ee(d,e[f])||d.push(e[f]);a.className=c.join(" ")},vf=function(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};
var wf=function(a){this.a=a;D||(delete this.a.lpu,delete this.a.ppu)},xf=["cn","tp"],yf=function(a,b){var c=null,d;if(s(document.postMessage)||s(window.postMessage)||D&&window.postMessage)d=1;else if(Na)d=2;else{if(c=D){c=!1;try{d=window.opener,window.opener={},c=Za(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new wf(d)};ga("GTalk_IFrameChannelConfig.build",yf);
var zf=function(){};q(zf,ke);zf.prototype.b=function(a){return a};qf(zf.prototype.b);zf.prototype.c=function(){return!0};qf(zf.prototype.c);var Af=function(a){y(this,a,0,[])};q(Af,x);var Bf=function(a,b){var c=new Af;O(c,1,b);O(c,2,a);return c},Cf=Bf("?",0),Df=Bf("q",1),Ef=Bf("<",2),Ff=Bf(">",3),Gf=Bf("~",4),Hf=Bf("s",5),If={g:Cf,k:Df,v:Ef,j:Ff,h:Gf,l:Hf};var Jf=function(a){y(this,a,"ci:dc",[])};q(Jf,x);B("ci:dc",Jf);var Kf=function(a){y(this,a,"ci:ec",[])};q(Kf,x);B("ci:ec",Kf);var Lf=function(a){return null!=z(a,2)?z(a,2):!1};var Mf=function(a,b,c){qe(this);var d=this.Cb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new of(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],g=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!ee(f,e)&&g.test(e)&&(d=Oe(d),d=Oe("https://"+e+d.P).toString())}this.da=d;this.c=c||new Kf;a.notificationsOnly&&O(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=ce(new Xd(window.location.href),"authuser"),null!=c&&(this.b=c));this.e=a.clientUrl||"notifierclient";c=ce(Oe(this.e),"authuser");null!=c&&(this.b=c);this.j=a.propertyName||"Google Talk";this.p=a.cssUrl;this.locale=a.locale;this.h=a.debug;this.Wb=a.userJid;this.Za=a.uiVersion;this.Rc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.S=a.hostLogMinValue;this.Wa=a.hideChat;this.Kc=a.refresh;this.L=a.hideProfileCard;this.O=a.hideStatusMsgs;this.M=a.hideRosterOptions;this.K=a.hideRecentConversations;
this.F=a.hideOTR;this.Hc=a.hostServerMessageCallback||!1;this.ba=a.isCentralRoster;this.Jc=a.isFullFrame||!1;this.Mc=a.rosterClass||"talk_roster";this.Va=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.g=a.parentToken;this.Dc=b||!1;p(a.isRtl)||jf.test(this.locale);this.v=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in If)b.push(If[k].I)}this.w=a.entityId;
this.Vb=a.useQuasarPanels||!1;this.Xa=a.silent||!1;this.Ic=a.ignoreCentralRoster||!1;this.Lc=a.lazy||!1;this.Gc=a.handleProfileLinks||!1;this.aa=a.hostSettings;this.k=a.screen;this.t=a.docsConfig;this.Da=a.jsmode;this.Ga=a.moleWidth;this.Fa=a.moleHeight;this.Ea=a.minimizedMoleHeight||36;this.Tc=a.derp;this.Ya=window.location.protocol+"//"+window.location.host;this.A=a.optOutAllowed;this.B=a.showWelcomePromo;this.l=a.conversationId};zf.q||q(zf,ke);Mf.ka=zf;
var Nf=function(a){switch(a){case 1:return"homepage";case 2:return"Orkut";case 3:return"iGoogle";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 29:return"potluck"}},Of=function(a){if(a.Da)a=a.Da;else{a=window.location.href; var b=a.search(Te),c=Ue(a,0,"jsmode",b);if(0>c)a=null;else{var d=a.indexOf("&",c);if(0>d||d>b)d=b;c+=7;a=decodeURIComponent(a.substr(c,d-c).replace(/\+/g," "))}}return a};
var Pf=function(a,b,c,d,e){this.a=a;this.b=d||window.document;this.c=new H(this);Q(this,this.c);var f=Ea;d=new Xd(a.da+a.e);Lf(a.c)||(R(d,"ts","0"),R(d,"re",a.Rc),R(d,"ref",a.Kc));R(d,"client","sm");R(d,"prop",a.j);R(d,"nav","true");R(d,"fid",a.a);a.h&&R(d,"debug",a.h);R(d,"os",Qa);R(d,"stime",c);a.Wa&&R(d,"hc",a.Wa);for(c=0;c<xf.length;++c);b=xd(b.a);R(d,"xpc",b);R(d,"ec",xd(a.c.I));a.k&&R(d,"screen",a.k);-1!=f.indexOf("MSIE")&&R(d,"ua",f);a.g&&R(d,"pvt",a.g);a.Hc&&R(d,"hsmc","true");p(a.S)&&R(d,
"logl",a.S);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),R(d,"href",b.join("?")));b=new Xd(window.location.href);"false"==ce(b,"uacheck")&&R(d,"uacheck",!1);(f=Of(a))&&R(d,"jsmode",f);(f=ce(b,"cssmode"))&&R(d,"cssmode",f);(f=ce(b,"convid"))&&R(d,"convid",f);(f=b.a.C("convp"))&&be(d,"convp",f);(f=ce(b,"smexp"))&&R(d,"smexp",f);f=b.a.C("mods");a.Lc&&f.push("lazy");e&&(f=Id(f,e));0<f.length&&R(d,"mods",f.join(","));if(!a.da||0>a.da.indexOf("/u/"))(e=
ce(b,"authuser"))?R(d,"authuser",e):null!=a.b&&R(d,"authuser",a.b);e=ce(b,"eid");null!=e&&R(d,"eid",e);null!=this.a.w&&R(d,"eid",this.a.w);null!=this.a.v&&R(d,"pos",this.a.v);p(a.Za)&&R(d,"uiv",this.a.Za);a.p&&R(d,"css",a.p);e=a.locale||ce(b,"hl");null!=e&&R(d,"hl",e);p(a.Wb)&&R(d,"uj",a.Wb);null!=a.L&&R(d,"hpc",a.L);null!=a.O&&R(d,"hsm",a.O);null!=a.M&&R(d,"hro",a.M);null!=a.K&&R(d,"hrc",a.K);null!=a.F&&R(d,"hotr",a.F);null!=a.ba&&R(d,"pop",a.ba);a.Dc&&R(d,"pal","1");null!=a.Vb&&R(d,"uqp",a.Vb);
null!=a.A&&R(d,"gooa",a.A);null!=a.B&&R(d,"gswp",a.B);null!=a.Xa&&R(d,"sl",a.Xa);a.Ic&&R(d,"icr","1");a.Gc&&R(d,"hpl","1");a.aa&&R(d,"hs",a.aa);a.t&&R(d,"dc",xd(a.t.I));null!=a.Ga&&R(d,"molew",a.Ga);null!=a.Fa&&R(d,"moleh",a.Fa);null!=a.Ea&&R(d,"mmoleh",a.Ea);a.Tc&&R(d,"derp","1");null!=a.Ya&&R(d,"two",a.Ya);null!=a.l&&R(d,"convid",a.l);R(d,"host","1");R(d,"zx",Wd());this.e=d.toString()};q(Pf,E);
var Qf=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Mc,a.b.body.appendChild(e));a=r(function(){var a="";this.a.Jc||(a="height:400px");var b=this.b.createElement("iframe");ef(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});if(!sf(e))for(var a=e,k;k=a.firstChild;)a.removeChild(k);e.appendChild(b);b=this.b.getElementById(this.a.a);Bd(this.c,b,["load","error"],vf(d),void 0);b.src=this.e.toString();c()},a);window.setTimeout(a, 0)};
var Rf=function(a){G.call(this,a[0]);this.lb=a};q(Rf,G);var Sf=function(a){y(this,a,"h_ccf",[])};q(Sf,x);B("h_ccf",Sf);var Tf=function(a){y(this,a,"h_rtp",[])};q(Tf,x);B("h_rtp",Tf);var Uf=function(a,b){this.B=m();this.A=a;this.document=b||window.document;this.a=new Mf(a,!0,a.endpointConfig);this.g=[];this.p=new I};q(Uf,E);Uf.prototype.n=function(){Uf.q.n.call(this);this.b&&this.k&&this.b.parentNode.removeEventListener("DOMAttrModified",this.k,!0)};Uf.prototype.c=function(a,b){this.e?this.e[a]&&this.e[a].apply(this.e,Array.prototype.slice.call(arguments,1)):this.g.push(arguments)};
Uf.prototype.h=function(){var a=this.ic().GTalkNotifier;if(a){var b=he(this.A);b.endpointConfig=this.a.c.I;this.e=new a(b,!0);for(a=0;a<this.g.length;a++)this.c.apply(this,this.g[a]);this.g=[];a=r(this.onMessage,this);this.c("_addClientMessageCallback",a);this.c("_addHostBundleMessageCallback",a)}};Uf.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":new Sf(a)}P(this.p,new Rf(a))};var Vf=function(a,b){a.c("_h",b.I)};h=Uf.prototype;h.sendMessage=function(a){Vf(this,a)};h.va=function(){return this.p};
h.ic=function(){return this.document.parentWindow||this.document.defaultView};h.cd=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new Tf;Vf(this,c)}};h.dd=function(){sf(this.document.getElementById(this.a.Va))&&(this.document.getElementById(this.a.a).style.display="none")};
var Wf=function(a){var b=a.a.da+"host-js",b=kf(b,"prop",a.a.j),c=Of(a.a);c&&(b=kf(b,"jsmode",c));Lf(a.a.c)&&(b=kf(b,"b","1"));var b=kf(b,"zx",Wd()),d=r(a.h,a),e=rf("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=r(a.t,a,e);a.document.body.appendChild(e)};Uf.prototype.t=function(){};
var Xf=function(a,b){this.b=b;this.a=a};Xf.prototype.G=function(){return this.a};var Yf=function(a){a.a=Math.min(a.b,2*a.a)};var Zf=function(a,b,c){var d={},e=null!=z(a,1)?z(a,1):"talkgadget.google.com",f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=z(a,2)&&27!=z(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";d.authUser=null!=z(a,8)?z(a,8):"0";d.clientUrl="chat";d.propertyName=Nf(z(a,2));d.locale=z(a,4);d.hideProfileCard=!0;d.parentToken=z(a,3);d.isRtl=null!=z(a,6)?z(a,6):!1;d.lazy=null!=z(a,7)?z(a,7):!1;d.entityId=z(a,9);d.hostSettings=z(a,5);d.jsmode=z(a,11);d.isFullFrame=null!=z(a,13)?z(a,13):
!1;d.rosterId=null!=z(a,12)?z(a,12):"talk_roster";d.rosterIframeIdB=null!=z(a,15)?z(a,15):"gtn-roster-iframe-id-b";d.derp=!(null==z(a,16)||!z(a,16));e=Ed(a,Pe,14);null!=e&&(d.isCentralRoster=null!=z(e,1)?z(e,1):!1,d.useQuasarPanels=null!=z(e,2)?z(e,2):!1);e=Ed(a,Re,10);null!=e&&(d.moleManagerLeftMargin=z(e,1),d.moleManagerMiddleMargin=z(e,2),d.moleManagerRightMargin=z(e,3),d.moleManagerNoMoleAreaMargin=z(e,4),d.moleManagerBoundingElementId=z(e,5),d.moleWidth=z(e,6),d.moleHeight=z(e,7),d.minimizedMoleHeight=
z(e,8));e=Ed(a,Qe,18);null!=e&&(d.optOutAllowed=null!=z(e,1)?z(e,1):!0,d.showWelcomePromo=z(e,2));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new Kf;O(e,2,!0);O(e,1,!0);O(e,3,!1);d.endpointConfig=e;d.ignoreAutomatedRoster=null!=z(a,17)?z(a,17):!1;d.conversationId=a.Z();d.hostCallback=c;Uf.call(this,d,b);this.l=new Xf(5E3,3E5);this.w=null};q(Zf,Uf);
Zf.prototype.t=function(a){var b=sf(this.document.body);b&&uf(b,"talk_network_warning");this.w=fe(function(){null==this.e&&(this.document.body.removeChild(a),Wf(this))},this.l.G(),this);Yf(this.l)};Zf.prototype.h=function(){Zf.q.h.call(this);var a=sf(this.document.body);a&&tf(a,"talk_network_warning")};Zf.prototype.n=function(){Zf.q.n.call(this);ge(this.w)};
var $f=function(a){y(this,a,"h_exts",[2])};q($f,x);B("h_exts",$f);var ag=function(){this.b=" "};q(ag,E);var bg=function(a,b,c){a.a=c;b=new Xd(b);b=ae(b,new Xd("/talkgadget/_/extension-start"));a=r(a.c,a);c=new xe;Ae.push(c);a&&c.listen("complete",a);kb(c.W,"ready",c.S,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};ag.prototype.c=function(a){if(!this.H){if(Ke(a.target))try{var b=JSON.parse(Le(a.target)),c=new $f(b);this.b=z(c,1)||""}catch(d){this.b=""}this.a&&(this.a(),this.a=null)}};
var cg=function(a){I.call(this);this.c=a?a:null;this.a=null;this.e=!1;this.b=[];this.g=r(this.Nc,this);this.h=r(this.Xb,this);this.j=null};q(cg,I);var dg=function(a){G.call(this,"message");this.message=a};q(dg,G);h=cg.prototype;h.n=function(){cg.q.n.call(this);ge(this.j);this.Xb(!0);for(var a=0;a<this.b.length;++a)F(this.b[a]);delete this.b;delete this.g;delete this.h};
h.sendMessage=function(a){if(null==a||null==a.message)return!1;ic(a,this.c,"p");this.a&&this.e?this.a.postMessage(a.message()):this.b.push(a);return!0};h.connect=function(){if(null==this.c)return!1;try{if(this.a=chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return M("Exception "+a),!1}this.e=!0;this.a.onMessage.addListener(this.g);this.a.onDisconnect.addListener(this.h);for(var b=this.b.shift();null!=b;)ic(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
h.Nc=function(a){P(this,new dg(hc(new gc,a)))};h.Xb=function(a){this.a&&(this.a.onMessage.removeListener(this.g),this.a.onDisconnect.removeListener(this.h),this.a.disconnect(),delete this.a);this.e=!1;a||(this.j=fe(this.wd,5E3,this))};h.wd=function(){this.connect()?P(this,{type:"reconnected"}):P(this,{type:"disconnected"})};
var eg=function(a){y(this,a,"h_cp",[])};q(eg,x);B("h_cp",eg);var fg=function(a){y(this,a,"rbc_d",[])};q(fg,x);B("rbc_d",fg);fg.prototype.setTitle=function(a){O(this,1,a)};var gg=function(a){y(this,a,"h_cd",[1,4,5])};q(gg,x);B("h_cd",gg);gg.prototype.Z=function(){return z(this,2)};var hg=function(a){y(this,a,"h_hn",[])};q(hg,x);B("h_hn",hg);var ig=function(a){y(this,a,"h_hs",[])};q(ig,x);B("h_hs",ig);var jg=function(a){y(this,a,"h_jm",[2])};q(jg,x);B("h_jm",jg);var kg=function(a){y(this,a,"h_oc",[])};q(kg,x);B("h_oc",kg);var lg=function(a){y(this,a,"h_opc",[])};q(lg,x);B("h_opc",lg);var mg=function(a){y(this,a,"h_ogc",[])};q(mg,x);B("h_ogc",mg);var ng=function(a){y(this,a,"h_sc",[])};q(ng,x);B("h_sc",ng);var og=function(a){y(this,a,"h_ssc",[5])};q(og,x);B("h_ssc",og);var pg=function(a){y(this,a,"h_sm",[1,3])};q(pg,x);B("h_sm",pg);var qg=function(a){I.call(this);this.a=a};q(qg,I);var rg=new L("O9EQob");var sg=function(a){y(this,a,"capi:clstup",[])};q(sg,x);B("capi:clstup",sg);var tg=function(a){y(this,a,"capi:r_clre",[])};q(tg,x);B("capi:r_clre",tg);var ug=function(a){y(this,a,"capi:r_rrst",[])};q(ug,x);B("capi:r_rrst",ug);var vg=function(a){y(this,a,"capi:r_rers",[])};q(vg,x);B("capi:r_rers",vg);var wg=function(a){y(this,a,"capi:r_recl",[])};q(wg,x);B("capi:r_recl",wg);var xg=function(a){y(this,a,"capi:r_rstr",[])};q(xg,x);B("capi:r_rstr",xg);
var yg=new L("nED8Yb"),zg=new L("xclgJb");var Ag=function(a){y(this,a,"h_ec",[])};q(Ag,x);B("h_ec",Ag);var Bg=function(a){y(this,a,"h_fr",[])};q(Bg,x);B("h_fr",Bg);var Cg=function(a){y(this,a,"capii_c_cel",[])};q(Cg,x);B("capii_c_cel",Cg);var Dg=function(a){y(this,a,"capi:rfc",[])};q(Dg,x);B("capi:rfc",Dg);var Eg=function(a){y(this,a,"capii_c_ucmc",[])};q(Eg,x);B("capii_c_ucmc",Eg);var Fg=function(a){y(this,a,"capii_c_rc",[])};q(Fg,x);B("capii_c_rc",Fg);Fg.prototype.Z=function(){return z(this,1)};
var Gg=function(a){I.call(this);this.c=a.get(yg);this.a=this.g=0;this.e=this.b=!1;a=new H(this);Q(this,a);a.listen(this.c.va(),"capii_c_ucmc",this.h);this.c.sendMessage(new Eg)};q(Gg,I);Gg.prototype.h=function(a){a=new Eg(a.lb);this.b||(this.b=!0,this.e&&(O(a,5,!0),this.e=!1));var b=this.g!=z(a,1);this.g=Number(z(a,1));var c=this.a!=z(a,2);this.a=Number(z(a,2));z(a,5)?P(this,"m"):(b&&P(this,"o"),c&&P(this,"n"))};
var Hg=function(a){y(this,a,"h_rha",[])};q(Hg,x);B("h_rha",Hg);var Ig=function(a){y(this,a,"h_ssf",[])};q(Ig,x);B("h_ssf",Ig);var Jg=function(a,b){this.a=new H(this);Q(this,this.a);this.a.listen(a.va(),"h_ssf",function(a){a=new Ig(a.lb);a=z(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new Hg;O(c,1,1);Vf(a,c)};q(Jg,E);var Kg=function(a){y(this,a,"h_ext",[])};q(Kg,x);B("h_ext",Kg);var Lg=function(a){y(this,a,"h_sru",[])};q(Lg,x);B("h_sru",Lg);var Mg=function(){H.call(this);M("Starting ace.core.DataChannel.");this.b=new id;Q(this,this.b);this.k=this.l=this.j=this.a=null;this.t=ec("quasar",""+(new Date).getTime());this.c=[];this.e=new cg(this.t);Q(this,this.e);this.g=null;this.e.connect();Eb(this,this.e,"message",this.K,!0,this);this.p=new ag;Q(this,this.p);this.listen(window,"unload",this.D);this.listen(window,"load",this.A)},Ng;q(Mg,H);var Og=function(a,b){null==a.c?b():a.c.push(b)};
Mg.prototype.A=function(){M("Initializing ace.core.DataChannel.");var a=new pc(Sc.wa().get("settings"));this.g=zd(a);F(a);bg(this.p,this.g,r(function(){if(!this.H&&-1!=this.g.lastIndexOf("talkgadget/")){var a=new Kf;O(a,2,!0);var a=new Cb,c=Oe(this.g),d=c.U;null!=c.fa&&(d+=":"+c.fa);O(a,1,d);O(a,2,23);d=chrome.i18n.getMessage("@@ui_locale");O(a,4,d);O(a,13,!0);O(a,17,!0);(d=this.p.b)&&O(a,3,d);c=ce(c,"jsmode");null!=c&&O(a,11,c);c=new Pe;O(c,2,!0);O(c,1,!0);Dd(a,14,c);a=new Zf(a,void 0,r(this.F,this));
t(void 0)&&(a.a.g=void 0);c=a.a;var e=a.a.da,d=a.a.b,f=Oe(e),g=f.P;if(0<=g.indexOf("/u/"))d=e;else{e=g.lastIndexOf("_/");if(0>e||e!=g.length-2)g+="_/";f.P="/u/"+d+g;d=f.toString()}c.da=d;a.a.e=a.a.e.replace("notifierclient","chat");a.j||(c=yf(a.a.da,a.a.a),a.j=new Pf(a.a,c,a.B,a.document,void 0),Q(a,a.j));Qf(a.j,a.a.Va,r(a.dd,a),r(a.c,a,"_rosterIframeLoaded"));Ob&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",a.b.src=a.a.da+"blank",a.b.style.cssText=
"width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.b),a.k=r(a.cd,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.k,!0));Wf(a);this.a=a;this.b.a(yg,this.a);this.j=new nf(this.a);this.b.a(Ne,this.j);this.listen(this.j,"i",this.B);this.l=new qg(this.a);this.b.a(rg,this.l);this.k=new Gg(this.b);this.b.a(zg,this.k);this.listen(this.k,"n",this.w);this.w();a=new Jg(this.a,r(this.M,this));Q(this,a);this.listen(this.a.va(),
"h_sru",this.O)}for(;this.c.length;)this.c.shift()();this.c=null},this))};Mg.prototype.F=function(a,b){if("extensionMessage"==a)if("__reload__"==b)chrome.runtime.reload();else{var c=new gc;hc(c,JSON.parse(b)||{});this.e.sendMessage(c)}};Mg.prototype.B=function(){var a=this.j.a;M("Receiving ClientState update:"+a);switch(a){case gf.LOADING:a=2;break;case gf.Fc:a=4;break;case gf.Ec:a=3;break;default:return}Pg(this,["changeDesktop",a],"desktopManager")};
Mg.prototype.K=function(a){var b=a.message;if("onSendHostMessage"==b.a)Og(this,r(function(){var a=new Kg,c=b.content().toString();O(a,1,c);this.a.sendMessage(a)},this));else if("onOpenConversation"==b.a){var c=b.content()[0];Og(this,r(function(){var a=this.l,b=new kg;O(b,1,c);Vf(a.a,b);b=new gg;O(b,1,[c]);var f=new lg;Dd(f,1,b);Vf(a.a,f)},this))}};var Pg=function(a,b,c){var d=new gc;ic(d,a.t,"p");Ad(d,"","e");kc(d,b);null!=c&&(d.v=c);jc(d,""+m());a.e.sendMessage(d)};
Mg.prototype.M=function(){M("Send user feedback event received");var a=fd();window.open(a)};Mg.prototype.O=function(a){a=new Lg(a.lb);Pg(this,["setRosterUrl",z(a,2)],"dataChannelManager")};Mg.prototype.w=function(){Pg(this,["setUnreadIndicator",!!this.k.a],"desktopManager")};
if(!p(Ng)||null==Ng||Ng.H)Ng=new Mg;
}catch(e){_DumpException(e)}
// Google Inc.
