try{
var h,ba=ba||{},l=this,ca="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
l.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"}, quasar_sign_in:{message:"Sign in"}};

}catch(e){_DumpException(e)}
try{
var p=function(a){return void 0!==a},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;
a.q=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Gd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(ma,Error);ma.prototype.name="CustomError";
var pa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",n=e[g]||"",A=RegExp("(\\d*)(\\D*)","g"),J=RegExp("(\\d*)(\\D*)","g");do{var aa=A.exec(k)||["","",""],K=J.exec(n)||["","",""];if(0==aa[0].length&&0==K[0].length)break;c=oa(0==aa[1].length?0:parseInt(aa[1],10),0==K[1].length?0:parseInt(K[1],10))||oa(0==aa[2].length,0==K[2].length)||oa(aa[2], K[2])}while(0==c)}return c},oa=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,qa=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var n=g[k];b.call(c,n,k,a)&&(e[f++]=n)}return e},ta=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,
f[g],g,a));return e},ua=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,g){e=b.call(d,e,c,g,a)});return e},va=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},wa=function(a,b){var c=qa(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var xa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var ya=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},za=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.I=b;t:{if(a.I.length&&(b=a.I.length-1,(c=a.I[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.e=b-a.b;a.c=c;break t}a.e=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.e?(c+=a.b,a.I[c]=a.I[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.e?a.I[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.I.toString()};var B=function(a,b){Ba[a]=b;b.Nb=a},Ba={};
var Ca="StopIteration"in l?l.StopIteration:Error("f"),Da=function(){};Da.prototype.next=function(){throw Ca;};Da.prototype.ia=function(){return this};var Ea;t:{var Fa=l.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){Ea=Ga;break t}}Ea=""}var Ha=function(a){return-1!=Ea.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.e=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.N(),d=a.C()):(c=Aa(a),d=za(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};h=C.prototype;h.X=function(){return this.c};h.C=function(){Ia(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};h.N=function(){Ia(this);return this.b.concat()};h.R=function(){return 0==this.c};
h.clear=function(){this.a={};this.e=this.c=this.b.length=0};h.remove=function(a){return Ja(this.a,a)?(delete this.a[a],this.c--,this.e++,this.b.length>2*this.c&&Ia(this),!0):!1};var Ia=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ja(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ja(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};h=C.prototype;h.get=function(a,b){return Ja(this.a,a)?this.a[a]:b};
h.set=function(a,b){Ja(this.a,a)||(this.c++,this.b.push(a),this.e++);this.a[a]=b};h.forEach=function(a,b){for(var c=this.N(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new C(this)};h.ia=function(a){Ia(this);var b=0,c=this.b,d=this.a,e=this.e,f=this,g=new Da;g.next=function(){for(;;){if(e!=f.e)throw Error("i");if(b>=c.length)throw Ca;var g=c[b++];return a?g:d[g]}};return g};var Ja=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Ka=function(a){if("function"==typeof a.C)return a.C();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return za(a)},La=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.N)d=a.N();else if("function"!=typeof a.C)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Aa(a);else d=void 0;for(var e=Ka(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Ma=Ha("Opera")||Ha("OPR"),D=Ha("Trident")||Ha("MSIE"),Na=Ha("Gecko")&&-1==Ea.toLowerCase().indexOf("webkit")&&!(Ha("Trident")||Ha("MSIE")),Oa=-1!=Ea.toLowerCase().indexOf("webkit"),Pa=l.navigator||null,Qa=Pa&&Pa.platform||"",Ra=function(){var a=l.document;return a?a.documentMode:void 0},Sa=function(){var a="",b;if(Ma&&l.opera)return a=l.opera.version,s(a)?a():a;Na?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Oa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Ea))?a[1]:"");return D&&(b= Ra(),b>parseFloat(a))?String(b):a}(),Ta={},Ua=function(a){return Ta[a]||(Ta[a]=0<=pa(Sa,a))},Va=l.document,Wa=Va&&D?Ra()||("CSS1Compat"==Va.compatMode?parseInt(Sa,10):5):void 0;
var E=function(){};E.prototype.H=!1;E.prototype.Kb=function(){return this.H};E.prototype.D=function(){this.H||(this.H=!0,this.n())};E.prototype.n=function(){if(this.v)for(;this.v.length;)this.v.shift()()};var F=function(a){a&&"function"==typeof a.D&&a.D()};
var Xa=!D||D&&9<=Wa;!Na&&!D||D&&D&&9<=Wa||Na&&Ua("1.9.1");D&&Ua("9");var Ya=function(a){Ya[" "](a);return a};Ya[" "]=ka;var Za=function(a,b){try{return Ya(a[b]),!0}catch(c){}return!1};var $a=!D||D&&9<=Wa,ab=D&&!Ua("9");!Oa||Ua("528");Na&&Ua("1.9b")||D&&Ua("8")||Ma&&Ua("9.5")||Oa&&Ua("528");Na&&!Ua("8")||D&&Ua("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.yc=!0};G.prototype.D=function(){};G.prototype.b=function(){this.yc=!1};var bb=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Na&&Za(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};q(bb,G); bb.prototype.b=function(){bb.q.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ab)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var cb="closure_listenable_"+(1E6*Math.random()|0),eb=function(a){return!(!a||!a[cb])},fb=0;var gb=function(a,b,c,d,e){this.ra=a;this.proxy=null;this.src=b;this.type=c;this.cb=!!d;this.kb=e;this.key=++fb;this.removed=this.bb=!1},hb=function(a){a.removed=!0;a.ra=null;a.proxy=null;a.src=null;a.kb=null};var ib=function(a){this.src=a;this.a={};this.b=0},kb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=jb(b,c,e,f);-1<k?(a=b[k],d||(a.bb=!1)):(a=new gb(c,a.src,g,!!e,f),a.bb=d,b.push(a));return a};ib.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=jb(e,b,c,d);return-1<b?(hb(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var lb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=wa(a.a[c],b);d&&(hb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};ib.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,hb(d[e]);delete this.a[c];this.b--}return b}; var mb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=jb(a,c,d,e));return-1<b?a[b]:null},jb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.ra==b&&f.cb==!!c&&f.kb==d)return e}return-1};
var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0,qb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);return null}c=rb(c);return eb(a)?a.listen(b,c,d,e):sb(a,b,c,!1,d,e)},sb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,k=tb(a);k||(a[nb]=k=new ib(a));c=kb(k,b,c,d,e,f);if(c.proxy)return c;d=ub();c.proxy=d;d.src=a;d.ra=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(vb(b.toString()),d);pb++;return c},ub=function(){var a=wb,b=$a?function(c){return a.call(b.src,
b.ra,c)}:function(c){c=a.call(b.src,b.ra,c);if(!c)return c};return b},xb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);else c=rb(c),eb(a)?a.Tb(b,c,d,e):a&&(a=tb(a))&&(b=mb(a,b,c,!!d,e))&&yb(b)},yb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(eb(b))return lb(b.W,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.cb):b.detachEvent&&b.detachEvent(vb(c),d);pb--;(c=tb(b))?(lb(c,a),0==c.b&&(c.src=null,b[nb]=null)):hb(a);return!0},vb=function(a){return a in
ob?ob[a]:ob[a]="on"+a},Ab=function(a,b,c,d){var e=1;if(a=tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.cb==c&&!f.removed&&(e&=!1!==zb(f,d))}return Boolean(e)},zb=function(a,b){var c=a.ra,d=a.kb||a.src;a.bb&&yb(a);return c.call(d,b)},wb=function(a,b){if(a.removed)return!0;if(!$a){var c;if(!(c=b))t:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new bb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;0<=k;k--)c.a=e[k],d&=Ab(e[k],f,!0,c);for(k=0;k<e.length;k++)c.a=e[k],d&=Ab(e[k],f,!1,c)}return d}return zb(a,new bb(b,this))},tb=function(a){a=a[nb];return a instanceof ib?a:null},Bb="__closure_events_fn_"+(1E9*Math.random()>>>0),rb=function(a){return s(a)?a:a[Bb]||(a[Bb]=function(b){return a.handleEvent(b)})};
var Cb=function(a){y(this,a,"h_cc",[])};q(Cb,x);B("h_cc",Cb);Cb.prototype.Z=function(){return z(this,19)};var H=function(a){this.L=a;this.h={}};q(H,E);var Db=[];H.prototype.listen=function(a,b,c,d){return Eb(this,a,b,c,d)};var Eb=function(a,b,c,d,e,f){u(c)||(c&&(Db[0]=c.toString()),c=Db);for(var g=0;g<c.length;g++){var k=qb(b,c[g],d||a.handleEvent,e||!1,f||a.L||a);if(!k)break;a.h[k.key]=k}return a};
H.prototype.Tb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Tb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.L||this,c=rb(c),d=!!d,b=eb(a)?mb(a.W,String(b),c,d,e):a?(a=tb(a))?mb(a,b,c,d,e):null:null,b&&(yb(b),delete this.h[b.key]);return this};H.prototype.removeAll=function(){ya(this.h,yb);this.h={}};H.prototype.n=function(){H.q.n.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){this.W=new ib(this);this.O=this;this.w=null};q(I,E);I.prototype[cb]=!0;h=I.prototype;h.addEventListener=function(a,b,c,d){qb(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){xb(this,a,b,c,d)};h.n=function(){I.q.n.call(this);this.W&&this.W.removeAll(void 0);this.w=null};h.listen=function(a,b,c,d){return kb(this.W,String(a),b,!1,c,d)};h.Tb=function(a,b,c,d){return this.W.remove(String(a),b,c,d)}; h.ea=function(a,b,c){a=this.W.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.cb==b){var g=f.ra,k=f.kb||f.src;f.bb&&lb(this.W,f);d=!1!==g.call(k,c)&&d}}return d&&!1!=c.yc};
var Fb,Gb,Hb,Ib,Jb,Kb,Lb;Lb=Kb=Jb=Ib=Hb=Gb=Fb=!1;var Mb=Ea;Mb&&(-1!=Mb.indexOf("Firefox")?Fb=!0:-1!=Mb.indexOf("Camino")?Gb=!0:-1!=Mb.indexOf("iPhone")||-1!=Mb.indexOf("iPod")?Hb=!0:-1!=Mb.indexOf("iPad")?Ib=!0:-1!=Mb.indexOf("Chrome")?Kb=!0:-1!=Mb.indexOf("Android")?Jb=!0:-1!=Mb.indexOf("Safari")&&(Lb=!0));var Ob=Fb,Pb=Gb,Qb=Hb,Rb=Ib,Sb=Jb,Tb=Kb,Ub=Lb;
var L=function(a){this.a=a};L.prototype.toString=function(){return this.a};var Vb=new L("b"),Wb=new L("c"),Xb=new L("h"),Yb=new L("k"),Zb=new L("G"),$b=new L("M"),ac=new L("N");var bc=new L("ea");var dc=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("o");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,A,J,aa){if("%"==A)return"%";var K=c.shift();if("undefined"==typeof K)throw Error("p");arguments[0]=K;return cc[A].apply(null,arguments)})},cc={s:function(a,b,c){return isNaN(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+Array(c-a.length+1).join(" "):Array(c-a.length+1).join(" ")+a},f:function(a,b,c,
d,e){d=a.toString();isNaN(e)||""==e||(d=a.toFixed(e));var f;f=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=f+d);if(isNaN(c)||d.length>=c)return d;d=isNaN(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=c-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Array(a+1).join(" "):f+Array(a+1).join(0<=b.indexOf("0",0)?"0":" ")+d},d:function(a,b,c,d,e,f,g,k){return cc.f(parseInt(a,10),b,c,d,0,f,g,k)}};cc.i=cc.d;cc.u=cc.d;
var ec=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},M=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=dc("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+dc(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+dc.apply({},c)))},fc=function(){return 0<=navigator.userAgent.indexOf("CrOS")};
var gc=function(a,b){this.e=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.g=null;this.j=b||"u";this.a=this.v=null;this.h=[]};gc.prototype.message=function(){var a={};a.i=this.a;a.m=this.h;a.r=this.j;a.o=this.v;a.s=this.b;a.st=this.c;a.d=this.g;a.dt=this.e;return a};ga("ace.base.Message.prototype.message",gc.prototype.message);
var hc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.a=b[c];break;case "m":a.h=b[c];break;case "o":a.v=b[c];break;case "s":a.b=b[c];break;case "d":a.g=b[c];break;case "st":a.c=b[c];break;case "dt":a.e=b[c]}return a},ic=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))},jc=function(a,b){null!=b&&(a.a=b)},kc=function(a,b){"object"==typeof b?a.h=b:a.h=[b]};gc.prototype.source=function(){return this.b};gc.prototype.target=function(){return this.g};gc.prototype.Ac=function(){return this.c}; gc.prototype.content=function(){return this.h};
var lc=function(a,b,c,d,e){this.b=a;this.Ua=b;this.a=typeof b;this.Ob=c?c:!1;this.ca=!0;this.Ib=d?d:!1;this.Bb=e?e:!1};q(lc,E);h=lc.prototype;h.n=function(){lc.q.n.call(this);this.b="";this.Ua=null;this.a=""};h.id=function(){return this.b};h.type=function(){return this.a};h.G=function(){return this.Ua};h.setEnabled=function(a){this.ca=a};
var mc=function(a){return(a=a.exec(Ea))?a[1]:""},nc=function(){if(Ob)return mc(/Firefox\/([0-9.]+)/);if(D||Ma)return Sa;if(Tb)return mc(/Chrome\/([0-9.]+)/);if(Ub)return mc(/Version\/([0-9.]+)/);if(Qb||Rb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ea))return a[1]+"."+a[2]}else{if(Sb)return(a=mc(/Android\s+([0-9.]+)/))?a:mc(/Version\/([0-9.]+)/);if(Pb)return mc(/Camino\/([0-9.]+)/)}return""}();
var pc=function(a){this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&oc(this,a)};q(pc,E);var qc=0<=pa(nc,"23.0.1262.0")&&!fc();pc.prototype.n=function(){pc.q.n.call(this);for(var a=this.a.N(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};pc.prototype.getItem=function(a){return Ja(this.a.a,a)?this.a.get(a):null};pc.prototype.setItem=function(a){this.a.set(a.id(),a)}; var oc=function(a,b){for(var c in b){var d=b[c],e=null;Ja(a.a.a,c)?(e=a.a.get(c),e.Ua=d.value,d.changed&&(e.Bb=d.changed)):(e=new lc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var rc=function(a){l.setTimeout(function(){throw a;},0)},uc=function(a,b){var c=a;b&&(c=r(a,b));s(l.setImmediate)?l.setImmediate(c):(sc||(sc=tc()),sc(c))},sc,tc=function(){if(l.Promise&&l.Promise.resolve){var a=l.Promise.resolve();return function(b){a.then(function(){try{b()}catch(a){rc(a)}})}}var b=l.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";
document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.ac;d.ac=null;a()};return function(a){e.next=
{ac:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};
var zc=function(a,b){vc||(uc(wc),vc=!0);xc.push(new yc(a,b))},vc=!1,xc=[],wc=function(){for(;xc.length;){var a=xc;xc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){rc(d)}}}vc=!1},yc=function(a,b){this.a=a;this.b=b};var Ac=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Bc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Dc=function(a,b){this.b=0;this.h=void 0;this.a=this.c=null;this.e=this.g=!1;try{var c=this;a.call(b,function(a){Cc(c,2,a)},function(a){Cc(c,3,a)})}catch(d){Cc(this,3,d)}},Fc=function(){var a,b=new Dc(function(b){a=b});return new Ec(b,a)};Dc.prototype.then=function(a,b,c){return Gc(this,s(a)?a:null,s(b)?b:null,c)};Ac(Dc);
var Jc=function(a){0==a.b&&zc(function(){var a=new Hc(void 0);Ic(this,a)},a)},Ic=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.eb)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?Ic(c,b):(d=c.a.splice(e,1)[0],Kc(c,d,3,b)))}}else Cc(a,3,b)},Mc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||Lc(a);a.a||(a.a=[]);a.a.push(b)},Gc=function(a,b,c,d){var e={eb:null,tc:null,vc:null};e.eb=new Dc(function(a,g){e.tc=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){g(A)}}:
a;e.vc=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof Hc?g(b):a(e)}catch(A){g(A)}}:g});e.eb.c=a;Mc(a,e);return e.eb};Dc.prototype.v=function(a){this.b=0;Cc(this,2,a)};Dc.prototype.j=function(a){this.b=0;Cc(this,3,a)};
var Cc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(Bc(c)){a.b=1;c.then(a.v,a.j,a);return}if(ha(c))try{var d=c.then;if(s(d)){Nc(a,c,d);return}}catch(e){b=3,c=e}}a.h=c;a.b=b;Lc(a);3!=b||c instanceof Hc||Oc(a,c)}},Nc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.v(b))},f=function(b){d||(d=!0,a.j(b))};try{c.call(b,e,f)}catch(g){f(g)}},Lc=function(a){a.g||(a.g=!0,zc(a.k,a))};
Dc.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)Kc(this,a[b],this.b,this.h)}this.g=!1};var Kc=function(a,b,c,d){if(2==c)b.tc(d);else{for(;a&&a.e;a=a.c)a.e=!1;b.vc(d)}},Oc=function(a,b){a.e=!0;zc(function(){a.e&&Pc.call(null,b)})},Pc=rc,Hc=function(a){ma.call(this,a)};q(Hc,ma);Hc.prototype.name="cancel";var Ec=function(a,b){this.b=a;this.a=b};
var Sc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Qc;this.b=!0;Rc(this)};Sc.wa=function(){return Sc.a?Sc.a:Sc.a=new Sc};var Rc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){var b=chrome.runtime?chrome.runtime.lastError:void 0;b&&M("chrome storage read error "+b);if(!this.b){for(var f in a)this.c.set(f,a[f]);this.b=!0}c()},a))};Sc.prototype.get=function(a){return this.a.get(a)};Sc.prototype.set=function(a,b){var c=Fc();this.a.set(a,b);c.a(void 0);return c.b};
Sc.prototype.remove=function(a){this.a.remove(a)};Sc.prototype.clear=function(){this.a.clear()};var Qc=function(){this.a=window.localStorage};Qc.prototype.clear=function(){this.a.clear()};Qc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ba[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a}; Qc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.I,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Qc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Tc=function(a,b){this.b=a;this.a=b;this.constructor.Zb||(this.constructor.Zb={});this.constructor.Zb[this.toString()]=this};Tc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var N=function(a,b){Tc.call(this,a,b)};q(N,Tc);var Uc=function(a){this.a=a},Vc=new Uc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Wc=function(a,b){this.e=[];this.w=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.h=!1;this.g=0;this.j=null;this.t=0};Wc.prototype.k=function(a,b){this.h=!1;Xc(this,a,b)};var Xc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Yc(a)},$c=function(a){if(a.a){if(!a.l)throw new Zc;a.l=!1}};Wc.prototype.v=function(a){$c(this);Xc(this,!0,a)};var ad=function(a,b,c,d){a.e.push([b,c,d]);a.a&&Yc(a)};
Wc.prototype.then=function(a,b,c){var d,e,f=new Dc(function(a,b){d=a;e=b});ad(this,d,function(a){"undefined"!=typeof bd&&a instanceof bd?Jc(f):e(a)});return f.then(a,b,c)};Ac(Wc);
var cd=function(a){return va(a.e,function(a){return s(a[1])})},Yc=function(a){if(a.g&&a.a&&cd(a)){var b=a.g,c=dd[b];c&&(l.clearTimeout(c.gb),delete dd[b]);a.g=0}a.j&&(a.j.t--,delete a.j);for(var b=a.c,d=c=!1;a.e.length&&!a.h;){var e=a.e.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var k=f.call(e||a.w,b);p(k)&&(a.b=a.b&&(k==b||k instanceof Error),a.c=b=k);Bc(b)&&(d=!0,a.h=!0)}catch(n){b=n,a.b=!0,cd(a)||(c=!0)}}a.c=b;d&&(k=r(a.k,a,!0),d=r(a.k,a,!1),b instanceof Wc?(ad(b,k,d),b.p=!0):b.then(k,d));c&&
(b=new ed(b),dd[b.gb]=b,a.g=b.gb)},Zc=function(){ma.call(this)};q(Zc,ma);Zc.prototype.message="Deferred has already fired";Zc.prototype.name="AlreadyCalledError";var ed=function(a){this.gb=l.setTimeout(r(this.b,this),0);this.a=a};ed.prototype.b=function(){delete dd[this.gb];throw this.a;};var dd={};

}catch(e){_DumpException(e)}
try{
var od={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pd=function(a,b){b.push('"',a.replace(xa,function(a){if(a in od)return od[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return od[a]=e+b.toString(16)}),'"')},qd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),rd=function(a,b,c){switch(typeof b){case "string":pd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),rd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),pd(e,c),c.push(":"),rd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}},sd=function(){},td=function(a,
b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)td(a,b[f],c,d,e);return null}c=rb(c);return eb(a)?kb(a.W,String(b),c,!0,d,e):sb(a,b,c,!0,d,e)},ud=Oa,vd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,O=function(a,b,c){b<a.e?a.I[b+a.b]=c:a.c[b]=c},wd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<qd.length;f++)c=qd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},xd=function(a){var b=
[];rd(new sd,a,b);return b.join("")},yd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},zd=function(a){a=a.b[0];M("getApplicationPath: "+a);return a},Ad=function(a,b,c){null!=b&&(a.g=b,null!=c&&(a.e=c))},P=function(a,b){var c,d=a.w;if(d)for(c=[];d;d=d.w)c.push(d);var d=a.O,e=b,f=e.type||e;if(t(e))e=new G(e,d);else if(e instanceof G)e.target=e.target||d;else{var g=e,e=new G(f,d);wd(e,g)}var g=!0,k;if(c)for(var n=
c.length-1;0<=n;n--)k=e.a=c[n],g=k.ea(f,!0,e)&&g;k=e.a=d;g=k.ea(f,!0,e)&&g;g=k.ea(f,!1,e)&&g;if(c)for(n=0;n<c.length;n++)k=e.a=c[n],g=k.ea(f,!1,e)&&g},Bd=function(a,b,c,d,e,f){if(u(c))for(var g=0;g<c.length;g++)Bd(a,b,c[g],d,e,f);else{b=td(b,c,d||a.handleEvent,e,f||a.L||a);if(!b)return a;a.h[b.key]=b}return a},Cd=function(a){if(ud){ud=!1;var b=l.location;if(b){var c=b.href;if(c&&(c=(c=Cd(c)[3]||null)&&decodeURIComponent(c))&&c!=b.hostname)throw ud=!0,Error();}}return a.match(vd)},Q=function(a,b){var c=
yd(F,b);a.v||(a.v=[]);a.v.push(p(void 0)?r(c,void 0):c)},Dd=function(a,b,c){var d=c?c.I:c;a.a[b]=c;O(a,b,d)},Ed=function(a,b,c){if(!a.a[c]){var d=z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Fd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Gd=function(a){return a?decodeURIComponent(a):""},Hd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Id=function(a){return v.concat.apply(v,arguments)},Jd=function(a,b,c){this.a=
a||null;this.b=!!c},Md=function(a){if(!a.J&&(a.J=new C,a.Q=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Ld(a,e);d=a;f=f?decodeURIComponent(f.replace(/\+/g," ")):"";Md(d);d.a=null;var e=Ld(d,e),g=d.J.get(e);g||d.J.set(e,g=[]);g.push(f);d.Q++}};h=Jd.prototype;h.J=null;h.Q=null;h.X=function(){Md(this);return this.Q};
h.remove=function(a){Md(this);a=Ld(this,a);return Ja(this.J.a,a)?(this.a=null,this.Q-=this.J.get(a).length,this.J.remove(a)):!1};h.clear=function(){this.J=this.a=null;this.Q=0};h.R=function(){Md(this);return 0==this.Q};var Nd=function(a,b){Md(a);b=Ld(a,b);return Ja(a.J.a,b)};Jd.prototype.N=function(){Md(this);for(var a=this.J.C(),b=this.J.N(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Jd.prototype.C=function(a){Md(this);var b=[];if(t(a))Nd(this,a)&&(b=Id(b,this.J.get(Ld(this,a))));else{a=this.J.C();for(var c=0;c<a.length;c++)b=Id(b,a[c])}return b};Jd.prototype.set=function(a,b){Md(this);this.a=null;a=Ld(this,a);Nd(this,a)&&(this.Q-=this.J.get(a).length);this.J.set(a,[b]);this.Q++;return this};Jd.prototype.get=function(a,b){var c=a?this.C(a):[];return 0<c.length?String(c[0]):b};var Od=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.J.set(Ld(a,b),Hd(c)),a.Q+=c.length)};
Jd.prototype.toString=function(){if(this.a)return this.a;if(!this.J)return"";for(var a=[],b=this.J.N(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.C(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.a=a.join("&")};Jd.prototype.clone=function(){var a=new Jd;a.a=this.a;this.J&&(a.J=this.J.clone(),a.Q=this.Q);return a};
var Ld=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c},Pd=function(a,b){b&&!a.b&&(Md(a),a.a=null,a.J.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Od(this,e,a))},a));a.b=b},Qd=/#/g,Rd=/[\#\?@]/g,Sd=/[\#\?]/g,Td=/[\#\?:]/g,Ud=/[#\/\?@]/g,Vd=function(a,b){return t(a)?encodeURI(a).replace(b,Fd):null},Wd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^m()).toString(36)},Xd=function(a,b){var c;"undefined"!=
typeof Xd&&a instanceof Xd?(this.oa=p(b)?b:a.oa,Yd(this,a.ga),this.ta=a.ta,this.U=a.U,Zd(this,a.fa),this.P=a.P,$d(this,a.a.clone()),this.na=a.na):a&&(c=Cd(String(a)))?(this.oa=!!b,Yd(this,c[1]||"",!0),this.ta=Gd(c[2]||""),this.U=Gd(c[3]||""),Zd(this,c[4]),this.P=Gd(c[5]||""),$d(this,c[6]||"",!0),this.na=Gd(c[7]||"")):(this.oa=!!b,this.a=new Jd(null,0,this.oa))};h=Xd.prototype;h.ga="";h.ta="";h.U="";h.fa=null;h.P="";h.na="";h.oa=!1;
h.toString=function(){var a=[],b=this.ga;b&&a.push(Vd(b,Ud),":");if(b=this.U){a.push("//");var c=this.ta;c&&a.push(Vd(c,Ud),"@");a.push(encodeURIComponent(String(b)));b=this.fa;null!=b&&a.push(":",String(b))}if(b=this.P)this.U&&"/"!=b.charAt(0)&&a.push("/"),a.push(Vd(b,"/"==b.charAt(0)?Sd:Td));(b=this.a.toString())&&a.push("?",b);(b=this.na)&&a.push("#",Vd(b,Qd));return a.join("")};
var ae=function(a,b){var c=a.clone(),d=!!b.ga;d?Yd(c,b.ga):d=!!b.ta;d?c.ta=b.ta:d=!!b.U;d?c.U=b.U:d=null!=b.fa;var e=b.P;if(d)Zd(c,b.fa);else if(d=!!b.P){if("/"!=e.charAt(0))if(a.U&&!a.P)e="/"+e;else{var f=c.P.lastIndexOf("/");-1!=f&&(e=c.P.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],k=0;k<f.length;){var n=f[k++];"."==n?e&&k==f.length&&g.push(""):".."==n?((1<g.length||1==g.length&&""!=g[0])&&g.pop(),
e&&k==f.length&&g.push("")):(g.push(n),e=!0)}e=g.join("/")}else e=f}d?c.P=e:d=""!==b.a.toString();d?$d(c,Gd(b.a.toString())):d=!!b.na;d&&(c.na=b.na);return c};Xd.prototype.clone=function(){return new Xd(this)};
var Yd=function(a,b,c){a.ga=c?Gd(b):b;a.ga&&(a.ga=a.ga.replace(/:$/,""))},Zd=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("j`"+b);a.fa=b}else a.fa=null},$d=function(a,b,c){b instanceof Jd?(a.a=b,Pd(a.a,a.oa)):(c||(b=Vd(b,Rd)),a.a=new Jd(b,0,a.oa))},R=function(a,b,c){a.a.set(b,c)},be=function(a,b,c){u(c)||(c=[String(c)]);Od(a.a,b,c)},ce=function(a,b){return a.a.get(b)},de=function(a,b,c){return 2>=arguments.length?v.slice.call(a,b):v.slice.call(a,b,c)},ee=function(a,b){return 0<=qa(a,
b)},fe=function(a,b,c){if(s(a))c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=r(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:l.setTimeout(a,b||0)},ge=function(a){l.clearTimeout(a)},he=function(a){var b={},c;for(c in a)b[c]=a[c];return b},ie=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,k=0;k<g;k++)a[f+k]=d[k];else a.push(d)}}, je=function(a,b){var c;t:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]};
var ke=function(){},ne=function(a){var b=a.ka,c=function(a){c.q.constructor.call(this,a);var b=this.V.length;this.a=[];for(var d=0;d<b;++d)this.V[d].Jd||(this.a[d]=new this.V[d](a))};q(c,b);for(var d=[];a;){if(b=a.ka){b.V&&ie(d,b.V);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&s(b[e])&&b[e]!==a){var f=!!b[e].Uc,g=le(e,b,d,f);(f=me(e,b,g,f))&&(c.prototype[e]=f)}}a=a.q&&a.q.constructor}c.prototype.V=d;return c},le=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),
!d));++f);return e},me=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.V[c[0]].prototype[a].apply(this,arguments)}:b[a].Wc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=this.a[c[e]];if(n=n?n[a].apply(n,d):this.V[c[e]].prototype[a].apply(this,d)){d=n;break t}}d=!1}return d}:b[a].Vc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=
this.a[c[e]],n=n?n[a].apply(n,d):this.V[c[e]].prototype[a].apply(this,d);if(null!=n){d=n;break t}}d=void 0}return d}:b[a].rc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var n=this.a[c[e]];n?n[a].apply(n,d):this.V[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],n=0;n<c.length;++n){var A=this.a[c[n]];e.push(A?A[a].apply(A,d):this.V[c[n]].prototype[a].apply(this,d))}return e}:d||b[a].Wc||b[a].Vc||b[a].rc? e=null:e=oe;return e},oe=function(){return[]};ke.prototype.Fb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var qe=function(a){if(!a.Cb){var b;for(b=a.constructor;b&&!b.ka;)b=b.q&&b.q.constructor;b.ka.dc||(b.ka.dc=ne(b));b=new b.ka.dc(a);a.Cb=b;a.Fb||(a.Fb=pe)}},pe=function(a){return this.Cb.Fb(a)};var re=function(){};re.prototype.a=null;var te=function(a){var b;(b=a.a)||(b={},se(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var ue,ve=function(){};q(ve,re);var we=function(a){return(a=se(a))?new ActiveXObject(a):new XMLHttpRequest},se=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("v");}return a.b};ue=new ve;
var xe=function(a){I.call(this);this.F=new C;this.k=a||null;this.b=!1;this.j=this.a=null;this.t="";this.e=0;this.c=this.p=this.g=this.l=!1;this.A=0;this.h=null;this.L="";this.B=this.ba=!1};q(xe,I);var ye=/^https?$/i,ze=["POST","PUT"],Ae=[];xe.prototype.S=function(){this.D();wa(Ae,this)};
xe.prototype.send=function(a,b,c,d){if(this.a)throw Error("w`"+this.t+"`"+a);b=b?b.toUpperCase():"GET";this.t=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?we(this.k):we(ue);this.j=this.k?te(this.k):te(ue);this.a.onreadystatechange=r(this.K,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Be(this);return}a=c||"";var f=this.F.clone();d&&La(d,function(a,b){f.set(b,a)});d=je(f.N(),Ce);c=l.FormData&&a instanceof l.FormData;!ee(ze,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.L&&(this.a.responseType=this.L);"withCredentials"in this.a&&(this.a.withCredentials=this.ba);try{De(this),0<this.A&&((this.B=Ee(this.a))?(this.a.timeout=this.A,this.a.ontimeout=r(this.M,this)):this.h=fe(this.M,this.A,this)),this.g=!0,this.a.send(a),this.g=!1}catch(g){Be(this)}};var Ee=function(a){return D&&Ua(9)&&ia(a.timeout)&&p(a.ontimeout)},Ce=function(a){return"content-type"==a.toLowerCase()};
xe.prototype.M=function(){"undefined"!=typeof ba&&this.a&&(this.e=8,P(this,"timeout"),Fe(this,8))};var Be=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Ge(a);He(a)},Ge=function(a){a.l||(a.l=!0,P(a,"complete"),P(a,"error"))},Fe=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,P(a,"complete"),P(a,"abort"),He(a))};xe.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),He(this,!0));xe.q.n.call(this)};
xe.prototype.K=function(){this.H||(this.p||this.g||this.c?Ie(this):this.aa())};xe.prototype.aa=function(){Ie(this)};
var Ie=function(a){if(a.b&&"undefined"!=typeof ba&&(!a.j[1]||4!=(a.a?a.a.readyState:0)||2!=Je(a)))if(a.g&&4==(a.a?a.a.readyState:0))fe(a.K,0,a);else if(P(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Ke(a)?(P(a,"complete"),P(a,"success")):(a.e=6,Ge(a))}finally{He(a)}}},He=function(a,b){if(a.a){De(a);var c=a.a,d=a.j[0]?ka:null;a.a=null;a.j=null;b||P(a,"ready");try{c.onreadystatechange=d}catch(e){}}},De=function(a){a.a&&a.B&&(a.a.ontimeout=null);ia(a.h)&&(ge(a.h),a.h=null)},Ke=function(a){var b=
Je(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=Cd(String(a.t))[1]||null,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!ye.test(a?a.toLowerCase():"");c=b}return c},Je=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},Le=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
var Me=function(a){y(this,a,"h_cs",[])};q(Me,x);B("h_cs",Me);var Ne=new L("HwdKC");
}catch(e){_DumpException(e)}
try{
var Qg=function(a){for(var b=a.a.N(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.G(),type:f.type(),multiple:f.Ob,disabled:!f.ca,inverse:f.Ib,changed:f.Bb}}return c},Rg=function(a,b){return t(b)?a.getElementById(b):b},S=function(a){return Rg(document,a)},T=function(a){var b;b=b||[];b.length||(b[0]="");var c=chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=l.ace_i18n[a.toLowerCase()])?c.message:l.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_DumpException(e)}
try{
var Sg=function(a){return(a=a.a.get("TopMost"))&&a.ca?a.G():!0},Tg=function(){return!0},Ug={},Vg=0,Wg=function(a){a&&a!=chrome.windows.WINDOW_ID_NONE&&chrome.windows.update(a,{focused:!0})},Xg=function(a){if(Ug[a])return Ug[a];a=String(a);if(!Ug[a]){var b=/function ([^\(]+)/.exec(a);Ug[a]=b?b[1]:"[Anonymous]"}return Ug[a]},Yg=function(a){return a[ca]||(a[ca]=++Vg)},Zg=function(a){chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&
d[e].url==a){Wg(b[c].id);return}}})},$g=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},ah=function(){return null!=navigator.platform.match(/Mac.*/)},bh=function(){return!fc()&&null!=navigator.platform.match(/Linux.*/)},ch=function(a,b){var c=[];if(ee(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Xg(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;
case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Xg(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(ch(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},dh=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+Yg(a):b.substr(0,1)+a},eh=function(a){if(a instanceof Da)return a;if("function"==
typeof a.ia)return a.ia(!1);if(ja(a)){var b=0,c=new Da;c.next=function(){for(;;){if(b>=a.length)throw Ca;if(b in a)return a[b++];b++}};return c}throw Error("g");},fh=function(a,b){return a>b?1:a<b?-1:0},gh=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),fe(r(Zg,null,a),1E3))},hh=function(a,b){null!=a&&(b?a=chrome.runtime.getURL("images_3/"+a):0==a.indexOf("images_3/")&&(a=chrome.runtime.getURL(a)));return a},U=function(a){return U.b(a)};U.b=function(a){return a+"_"};
U.v=function(){throw Error("x");};U.g=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[U.b(c)]=a[c]);return b}throw Error("y");};U.c=!0;U.e=function(){};U.h=function(){return!0};var ih=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};ih.prototype.clone=function(){return new ih(this.left,this.top,this.width,this.height)};
ih.prototype.contains=function(a){return"undefined"!=typeof ih&&a instanceof ih?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};ih.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
ih.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var jh=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/],kh=[1E4,12E4,144E5],lh=[200,2E3,3E5],mh=function(a,b){I.call(this);this.c=a||1;this.b=b||l;this.g=r(this.j,this);this.h=m()};q(mh,I);mh.prototype.e=!1;mh.prototype.a=null;
mh.prototype.setInterval=function(a){this.c=a;this.a&&this.e?(this.stop(),nh(this)):this.a&&this.stop()};mh.prototype.j=function(){if(this.e){var a=m()-this.h;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.g,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),P(this,"tick"),this.e&&(this.a=this.b.setTimeout(this.g,this.c),this.h=m()))}};var nh=function(a){a.e=!0;a.a||(a.a=a.b.setTimeout(a.g,a.c),a.h=m())};
mh.prototype.stop=function(){this.e=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};mh.prototype.n=function(){mh.q.n.call(this);this.stop();delete this.b};var oh=function(a){this.a=a||l.document||document};oh.prototype.ic=function(){var a=this.a;return a.parentWindow||a.defaultView};
oh.prototype.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var ph=function(a,b){this.width=a;this.height=b};ph.prototype.clone=function(){return new ph(this.width,this.height)};ph.prototype.R=function(){return!(this.width*this.height)};
ph.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};ph.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var qh=function(a){var b;b||(b=ch(a||arguments.callee.caller,[]));return b},rh=function(a){this.a=new C;if(a){a=Ka(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(dh(d),d)}}};h=rh.prototype;h.X=function(){return this.a.X()};
h.removeAll=function(a){a=Ka(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};h.remove=function(a){return this.a.remove(dh(a))};h.clear=function(){this.a.clear()};h.R=function(){return this.a.R()};h.contains=function(a){a=dh(a);return Ja(this.a.a,a)};h.C=function(){return this.a.C()};h.clone=function(){return new rh(this)};h.ia=function(){return this.a.ia(!1)};
var sh=function(a,b){if(ja(a))try{w(a,b,void 0)}catch(c){if(c!==Ca)throw c;}else{a=eh(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==Ca)throw d;}}},th=function(a,b,c){c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].I;a.a[b]=c;O(a,b,d)},uh=function(a,b,c){if(!a.a[c]){for(var d=z(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}return a.a[c]},vh=function(a){var b=arguments.length;if(1==b&&u(arguments[0]))return vh.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]= !0;return c},wh=function(a,b){a.sort(b||fh)},xh=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var yh=function(a){y(this,a,"dpgi",[])};q(yh,x);B("dpgi",yh);var zh=function(a){y(this,a,"dri",[])};q(zh,x);B("dri",zh);var Ah=function(a){y(this,a,"di",[6,7,10,11,12])};q(Ah,x);B("di",Ah);var Bh=function(a){y(this,a,"e",[])};q(Bh,x);B("e",Bh);var Ch=function(a){y(this,a,"f.ri",[])};q(Ch,x);B("f.ri",Ch);var Dh=function(){};q(Dh,E);
var Gh=function(a,b){var c=Eh;if(!(c.H||"undefined"!=typeof bd&&b instanceof bd))if(c.b){var c=c.b,d=Fh();d["call-stack"]=qh();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,g="";e&&(g=(e.lineNumber||"unknown")+":"+xh(e.fileName||"unknown")+":"+xh(e.message||"unknown"));var k="";for(f in d){var n;n="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];k=k+f+":"+n+":"}f=g+"::"+k;g=c.c[f];g||(g={time:0,count:0},c.c[f]=g);if(1E4>m()-g.time)g.count++,1==g.count&&(d=Fh(),d.message="Throttling: "+ f,c.a.a(e,d));else{g.count&&(d["dropped-instances"]=g.count);g.time=m();for(f=g.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])},Eh=new Dh;
var Hh=function(a){var b=window;if(!b.location){var c;try{c=xd(b)}catch(d){c=Aa(b).toString()}Gh(null,Error("z`"+c))}c=b.location&&b.location.ancestorOrigins;if(p(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return p((a?b.parent:b.top).location.href)}catch(e){return!1}};
var Ih={},Fh=function(){var a={};a.location=document.location.toString();if(Hh(!1))try{a["top.location"]=top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in Ih)try{a[c]=Ih[c].call()}catch(d){a[c]="[error] "+d.message}return a};
vh("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));vh("action","cite","data","formaction","href","manifest","poster","src");vh("link","script","style");var Jh={},Kh=function(a){Jh.ja(a)};var Lh=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; Lh.prototype.isMinimized=function(){return"minimized"==this.state};
var Mh=function(){this.a=new rh};q(Mh,E);Mh.prototype.ea=function(a){var b,c=Array.prototype.slice.call(arguments);w(this.a.C(),function(a){b=a.apply(null,c)});return b};Mh.prototype.addListener=function(a){this.a.a.set(dh(a),a)};Mh.prototype.removeListener=function(a){this.a.remove(a)};Mh.prototype.n=function(){this.a.clear();Mh.q.n.call(this)};
var Ph=function(){this.b=[];this.j=new Mh;Q(this,this.j);this.g=new Mh;Q(this,this.g);this.onClosed=new Mh;this.h=!1;this.c=null;this.k=r(this.B,this);Nh.addListener(this.k);this.l=r(this.A,this);Oh.addListener(this.l)};q(Ph,E);Ph.prototype.n=function(){Qh(this)||void 0!=this.a&&chrome.windows.remove(this.a);Rh(this);this.k&&(Nh.removeListener(this.k),Oh.removeListener(this.l));F(this.onClosed);Ph.q.n.call(this)};var Nh=chrome.windows&&chrome.windows.onRemoved,Oh=chrome.windows&&chrome.windows.onFocusChanged;
Ph.prototype.create=function(a){chrome.windows.create(a,r(function(a){this.H?chrome.windows.remove(a.id):(this.a=a.id,Sh(this))},this))};var Sh=function(a){if(null!=a.b&&Th(a))if(Qh(a))Rh(a);else{for(;a.b.length&&!Qh(a);)a.b.shift()(a);a.b=null}},Th=function(a){return!(!ia(a.a)||!a.e)},Uh=function(a,b){Qh(a)?Rh(a):null==a.b?b(a):a.b.push(b)},Qh=function(a){return!(!a.e||!a.e.closed)};Ph.prototype.B=function(){Qh(this)&&Rh(this)};
var Rh=function(a){if(!a.h){var b=a.onClosed;a.onClosed=new Mh;fe(r(function(){this.h||(this.h=!0,b.ea(this));F(b)},a))}};Ph.prototype.A=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.g.ea(this)}else this.c=!0,this.j.ea(this)};var Vh=function(a){var b;b=a.a?a.e:null;return!b||Qh(a)?null:b};Ph.prototype.minimize=function(){Uh(this,r(function(){return chrome.windows.update(this.a,{state:"minimized"})},this))};
Ph.prototype.focus=function(){Uh(this,r(function(){chrome.windows.update(this.a,{focused:!0})},this))};var Wh=function(a,b){Uh(a,r(function(){chrome.windows.update(this.a,{drawAttention:b})},a))},Yh=function(a,b){Uh(a,yd(Xh,[a],function(a){b(a[0])}))},Xh=function(a,b){chrome.windows.getAll(function(c){var d={};w(c,function(a){d[a.id]=a});var e=[];w(a,function(a){var b;a&&Th(a)&&!Qh(a)&&(b=d[a.a]);var c;b&&(c=new Lh(b));e.push(c)});b(e)})};
var Zh=function(a,b,c){this.b=a;this.e=b||0;this.c=c;this.ja=r(this.g,this)};q(Zh,E);Zh.prototype.a=0;Zh.prototype.n=function(){Zh.q.n.call(this);this.stop();delete this.b;delete this.c};var $h=function(a,b){a.stop();a.a=fe(a.ja,p(b)?b:a.e)};Zh.prototype.stop=function(){0!=this.a&&ge(this.a);this.a=0};Zh.prototype.g=function(){this.a=0;this.b&&this.b.call(this.c)};
var ai=function(a,b,c){I.call(this);this.a=b.createElement("IFRAME");t(a)?this.a.src=a:a.attach(this.a);c&&(this.a.id=c,this.a.name=c);b.body.appendChild(this.a);a=new H(this);Q(this,a);a=Bd(a,this.a,"load",this.c,void 0);Bd(a,this.a,"error",yd(Kh,1),void 0).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};q(ai,I);ai.prototype.b=function(){uc(this.a.focus,this.a)};ai.prototype.c=function(){this.b();P(this,"r")}; ai.prototype.n=function(){this.a.parentElement.removeChild(this.a);this.a=null;ai.q.n.call(this)};
var bi=new L("fa"),ci=new L("ga"),di=new L("ha"),ei=new L("ia"),fi=new L("ja"),gi=new L("ka"),hi=new L("la"),ld=new L("ma"),ii=new L("na");var ji=function(a,b){this.a=a;this.t=b;this.l=this.p=this.g="";this.b=null;this.h="";this.v=0;this.c=[];this.j=!1;this.k=""},ki=function(a,b){this.name=a;this.title=b||""};h=ji.prototype;h.setTitle=function(a){this.p=a};h.yb=function(){return this.p||""};h.Ma=function(){return this.h||""};h.type=function(){return this.t};h.xa=function(){if(this.Lb())return null;var a=this.a;null!=this.e?a+=this.e:null!=this.h&&(a+=this.h);return a};h.Lb=function(){return!1};
var li=function(a){return a.replace(/^(\<br\>)+/,"")},mi=function(a){var b=a.yb();a.l&&(b+=" "+(a.l||""));var c=li(a.Ma()),d=ta(a.c,function(a){var b;if(!(b=a.title))t:{switch(a.name){case "answer":case "join hangout":b=T("QUASAR_ANSWER_BUTTON_TEXT");break t;case "ignore":b=T("QUASAR_DECLINE_BUTTON_TEXT");break t}b=""}return{title:b}},a);return{type:"basic",iconUrl:(0==a.g.indexOf("data:")||0==a.g.indexOf("chrome-extension:")?a.g:"")||chrome.runtime.getURL("images_3/icon-128x128.png"),title:b,message:c, buttons:d,priority:2}};
var ni=function(a){ji.call(this,a,2)};q(ni,ji);ni.prototype.yb=function(){var a=ni.q.yb.call(this);return this.j&&!a?T("QUASAR_GROUP_CHAT_TITLE"):a};ni.prototype.Ma=function(){return 0<=this.a.indexOf("video")?T("QUASAR_VIDEO_DETAILS"):0<=this.a.indexOf("voice")?T("QUASAR_VOICE_DETAILS"):ni.q.Ma.call(this)};ni.prototype.Lb=function(){return 0<=this.a.indexOf("voice")||0<=this.a.indexOf("video")};
var V;var oi=function(a){ji.call(this,a,2)};q(oi,ji);oi.prototype.xa=function(){return null!=this.e?oi.q.xa.call(this):null};var pi=function(a){this.c=a;this.a=new pc;this.b=a.get(bc);this.a.setItem(new lc("StartOnBrowserLaunch",!0,!1,!1));qc&&this.a.setItem(new lc("TopMost",!0));a=new lc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new lc("TrayIcon",!0,!1,!1);a.setEnabled(null!=navigator.platform.match(/Win.*/)||bh()||ah());this.a.setItem(a);(a=this.b.get("settings"))&&oc(this.a,a);this.b.set("settings",Qg(this.a))};ga("ace.core.SettingsManager",pi);
var qi=chrome.runtime&&chrome.runtime.getURL&&chrome.runtime.getURL("settingsdialog.html")||"";pi.prototype.g=function(){this.b.set("settings",Qg(this.a));var a=V.e("setting");if(a&&0!=a.length)ri(a[0],"focus");else{var a=Math.floor((screen.height-200)/2),b=Math.floor((screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");gh(qi,c.join(","))}};pi.prototype.launchSettingsDialog=pi.prototype.g;
pi.prototype.h=function(){var a=new pc(Qg(this.a)),b=this.b.get("settings");oc(this.a,b);var c=new pc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ca&&(c.G()||b.G()?(b=this.c.get(ci),si(b),ti(b)):c.G()||b.G()||ui(this.c.get(ci)))};pi.prototype.updateSettingsFromStorage=pi.prototype.h;pi.prototype.e=function(){var a=V.e("setting");if(a)for(var b=0;b<a.length;++b)ri(a[b],"close")};pi.prototype.closeUI=pi.prototype.e; var ri=function(a,b){var c=new gc;jc(c,b);kc(c,[]);V.b(a).sendMessage(c)};
var W=new Uc("act"),vi=new Uc("impr"),wi=new Uc("tran"),xi=new Uc("perf");new N(W,1);new N(W,2);new N(W,3);new N(W,4);new N(W,5);new N(W,6);new N(W,7);new N(W,8);new N(W,9);new N(W,10);new N(W,11);new N(W,12);new N(W,13);new N(W,14);new N(W,15);new N(W,22);new N(W,16);new N(W,17);new N(W,18);new N(W,19);new N(W,20);new N(W,21);new N(W,23);new N(W,24);var yi=new N(vi,1E3);new N(wi,1001);new N(xi,1002);
var zi=new L("oa");var X=function(a){this.k=a;this.p=a.get(hi);this.b=a.get(bc);this.a=1;this.e=this.j=null;this.h=this.c=!1;this.l=r(this.t,this);si(this);ti(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};q(X,E);ga("ace.core.DesktopManager",X);X.prototype.n=function(){ui(this);X.q.n.call(this)};
X.prototype.g=function(a,b){this.a!=b&&(M("Desktop changing status from: %s to: %s, source: ",this.a,b,a&&a.Ac||""),this.a=b,ti(this),Ai(this),1==this.a&&(this.e=this.j=null,this.h=this.c=!1,ui(this),this.p.e(),this.k.get(fi).b()),V.h())};X.prototype.changeDesktop=X.prototype.g;X.prototype.w=function(a,b){this.c!=b&&(this.c=b,ti(this),Ai(this))};X.prototype.setMainUiShowing=X.prototype.w;
var si=function(a){var b=a.p.a,c;if(c=null!=navigator.platform.match(/Win.*/)||bh()||ah())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ca?c.G():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ca?b.G():!1);c&&chrome.systemIndicator&&(chrome.systemIndicator.enable(),chrome.systemIndicator.onClicked.addListener(a.l))},ui=function(a){chrome.systemIndicator&&(chrome.systemIndicator.disable(),chrome.systemIndicator.onClicked.removeListener(a.l))},Ai=function(a){var b;switch(a.a){case 2:b=T("QUASAR_TIP_CONNECTING");break;
case 3:b=T("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.h?T("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):T("QUASAR_TIP_CONNECTED"):T("QUASAR_TIP_NOT_LOGIN");break;case 6:b=T("QUASAR_TIP_NOT_LOAD");break;default:b=T("QUASAR_TIP_DISCONNECTED")}a=a.e?"\n"+a.e:"";(b=T("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&chrome.browserAction.setTitle({title:b})};
X.prototype.B=function(a,b,c){1==this.a?M("Invalid to set user name when the application isn't started"):(a=b||T("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.j&&(this.j=a),this.e=c)};X.prototype.updateUserName=X.prototype.B;X.prototype.A=function(a,b){this.h!=b&&(this.h=b,ti(this),Ai(this))};X.prototype.setUnreadIndicator=X.prototype.A;
var ti=function(a){chrome.browserAction.setIcon(Bi(a,!0));chrome.systemIndicator&&chrome.systemIndicator.setIcon(Bi(a))},Ci=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.h?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},Bi=function(a,b){var c=!b&&ah()?"_mac_":"_",d=Ci(a),e=chrome.runtime.getURL("images_3/presence/"+d+c+"19.png"),c=chrome.runtime.getURL("images_3/presence/"+d+c+"38.png");return{path:{19:e, 38:c}}};X.prototype.t=function(){var a=V.a();this.k.get(zi).a("qstcl");a.xb();a.b("onTrayClick",[1])};
var Di=function(){var a=new ai(chrome.runtime.getURL("datachannel.html"),document,"centralRoster");Q(this,a)};q(Di,E);var Ii=function(a,b){H.call(this);this.b=a;this.l=ec("viewer",""+(new Date).getTime());this.e=this.g=null;this.p=V;this.A=m();this.k=a.get(ci);var c=a.get(gi),d=T("CHROME_EXT_SHORT_NAME"),e=hh("viewer-14.png",!0),f=hh("viewer-24.png",!0),d=Ei(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?Ed(b,Fi,2).Oa():null,e=Gi(c,new ph(260,460),!0,e);Hi(c,d.id,e);this.a=d;this.a.onClosed.addListener(r(this.D,this));Uh(this.a,r(this.t,this))};q(Ii,H);
Ii.prototype.n=function(){this.b.b(ld)==this&&this.b.w();this.removeAll();Ii.q.n.call(this)};var Ji=function(a){F(a.g);a.g=null;F(a.e);a.e=null;Rg(a.c.a,"retryInfo").style.display="none"};Ii.prototype.close=function(){F(this.a);this.b.b(ld)==this&&this.b.w()};
Ii.prototype.t=function(){this.c=new oh(Vh(this.a).document);this.a.setTitle(T("CHROME_EXT_SHORT_NAME"));Rg(this.c.a,"retryMessage").textContent=T("CHROME_EXT_CANNOT_CONNECT");var a=Rg(this.c.a,"retryLink");a.textContent=T("QUASAR_TRY_NOW");this.listen(a,"click",this.w);this.listen(this.p,"onStatusChange",this.j);this.j()};Ii.prototype.w=function(a){a.b();this.b.get(bi).g()};
Ii.prototype.j=function(){switch(this.k.a){case 3:if(!this.g){Ji(this);var a;a=this.b.get(hi).a;a=new Xd(zd(a));var b=new Xd("/talkgadget/qsignin");R(b,"passive","1");R(b,"hl",chrome.i18n.getMessage("@@ui_locale"));a=ae(a,b).toString();this.g=new ai(a,this.c.a)}break;case 2:Ji(this);break;case 6:Ji(this);Rg(this.c.a,"retryInfo").style.display="block";break;default:Ki(this)}}; var Ki=function(a){a.e||(M("Requesting view: "+a.l),Ji(a),Li(a.b.get(bi)).then(function(a){this.e=new ai(a,this.c.a,"popoutRoster")},void 0,a))};
var Mi=function(a,b){this.b=Hd(a);this.a=0;this.c=b||!1};Mi.prototype.G=function(){var a=this.b[this.a];return a*=.5+1*Math.random()};var Ni=function(a){a.c&&a.a==a.b.length-1||a.a++};var Oi=function(a,b,c){this.c=a;this.b=b;this.a=c;this.ja=r(this.$c,this)};q(Oi,E);h=Oi.prototype;h.rb=!1;h.ya=null;h.stop=function(){this.ya&&(ge(this.ya),this.ya=null,this.rb=!1)};h.n=function(){Oi.q.n.call(this);this.stop()};h.$c=function(){this.ya=null;this.rb&&(this.rb=!1,Pi(this))};var Pi=function(a){a.ya=fe(a.ja,a.b);a.c.call(a.a)};
var Y=function(a){H.call(this);this.b=a;this.c=a.get(ci);this.S=a.b(gi);this.M=Fc();this.l=null;this.O=new Oi(this.g,6E4,this);Q(this,this.O);this.j=!1;this.t=new Mi(kh,!0);this.K=new Zh(this.Ya,this.t.G(),this);Q(this,this.K);this.k=new Zh(this.Xa,2E4,this);Q(this,this.k);this.listen(window,"online",this.Wa);this.B=this.F=0;this.a=new Mi(lh);this.e=new Zh(this.Fa,this.a.G(),this);Q(this,this.e);chrome.cookies.onChanged.addListener(r(this.Ga,this));this.A=r(this.ba,this);this.w=r(this.aa,this);chrome.tabs.onUpdated.addListener(this.A);
chrome.tabs.onCreated.addListener(this.w)};q(Y,H);ga("ace.core.DataChannelManager",Y);Y.prototype.n=function(){chrome.tabs.onCreated.removeListener(this.w);chrome.tabs.onUpdated.removeListener(this.A);delete this.w;delete this.A;F(this.l);Y.q.n.call(this)};Y.prototype.p=function(a,b){Qi(this);t:{var c=this.b,d=c.b(ld);if(d){if(Th(d.a)?!Qh(d.a):1E3>m()-d.A){d.a.focus();break t}d.close()}d=new Ii(c,b);c.a(ld,d,!0)}};Y.prototype.showViewer=Y.prototype.p;Y.prototype.Za=function(a,b){this.M.a(b||"")};
Y.prototype.setRosterUrl=Y.prototype.Za;var Li=function(a){return a.M.b};Y.prototype.Ea=function(){this.c.g(null,1);var a=this.b.b(ld);a&&a.close();Ri(this);this.j=!1};Y.prototype.terminateApplication=Y.prototype.Ea;var Qi=function(a){M("Starting application.");a.j||(a.listen(V,"onStatusChange",a.Da),a.g(),a.b.get(hi),a.j=!0)};Y.prototype.g=function(){this.H||(M("Reload wabel iframe..."),this.c.g(null,2),Ri(this),this.l=new Di)};
var Ri=function(a){a.S.g();a.b.get(fi).b();F(a.l);a.l=null;a.M=Fc()},Ti=function(a,b){var c=zd(a.b.get(hi).a);chrome.cookies.getAll({url:c},r(function(a){a=a&&Si("SID",a)&&Si("SSID",a)&&Si("SAPISID",a);b(a)},a))};Y.prototype.Va=function(a){var b=this.c.a;if(a){if(a=3==b)if(a=0==this.e.a)a=this.a,a=a.a<a.b.length;a&&(M("All cookies valid, reloading in %f s",this.a.G()/1E3),$h(this.e,this.a.G()))}else 3!=b&&(M("User logged out."),this.g())};
Y.prototype.Ga=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Ti(this,r(this.Va,this))};var Si=function(a,b){return va(b,function(b){var d=b.expirationDate&&b.expirationDate<m()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};Y.prototype.Da=function(){this.K.stop();this.k.stop();switch(this.c.a){case 2:$h(this.k);break;case 6:$h(this.K,this.t.G());break;case 4:case 9:case 8:case 5:this.t.a=0,this.e.stop()}};
Y.prototype.Wa=function(){if(4!=this.c.a){var a=this.O;a.ya?a.rb=!0:Pi(a)}};Y.prototype.Ya=function(){Ni(this.t);this.g()};Y.prototype.Xa=function(){this.H||(this.k.stop(),this.c.g(null,6))};var Ui=function(a){a.B++;var b=a.b.get(zi);1==a.B?b.a("qccro"):2==a.B?b.a("qccrt"):b.a("qccrm")};Y.prototype.Fa=function(){M("Reloading iframe due to cookie change...");Ni(this.a);Ui(this);Ti(this,r(function(a){a&&this.g()},this))};Y.prototype.ba=function(a,b){b.url&&Vi(this,b.url)};
Y.prototype.aa=function(a){a.url&&Vi(this,a.url)};var Wi=function(a){a.F++;var b=a.b.get(zi);1==a.F?b.a("qctro"):2==a.F?b.a("qctrt"):b.a("qctrm")},Vi=function(a,b){va(jh,function(a){return a.test(b)})&&0!=a.a.a&&(a.a.a=0,Wi(a),0!=a.e.a&&$h(a.e,a.a.G()))};
var Xi=function(a){this.a=0;this.c=a.get(bc);null!=this.c.a.get("dupDetectionQueue.latestChat")&&(this.a=this.c.get("dupDetectionQueue.latestChat"));this.b=0;this.g=new C;this.e=new mh(18E5);qb(this.e,"tick",r(this.h,this,this.g,0,200));nh(this.e)};q(Xi,E);Xi.prototype.n=function(){this.e.D()};var Yi=function(a,b){var c=b.xa();if(null==c)return!1;switch(b.type()){case 7:case 2:if(null!=b.b&&b.b<=a.a)if(31536E7<a.a-b.b)a.a=0,a.b=0;else return!0;else return Ja(a.g.a,c)}return!1};
Xi.prototype.h=function(a,b,c){M("Start cleaning queue.");var d=a.X();if(0==d)M("Empty queue.");else{var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b,M("minSize and maxSize conflict. Obey maxSize."));var f=[];c=a.ia(!0);sh(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear(),M("Clean the duplicate queue due to the big time difference");else{c=0;b=d-b;for(var d=d-e,e=m(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<= e)a.remove(f[g][0]),c+=1;else break;M("Clean Queue: "+c)}}};
var Zi=function(a){y(this,a,"acr:bcr",[])};q(Zi,x);B("acr:bcr",Zi);var $i=function(a){y(this,a,"acr:srs",[])};q($i,x);B("acr:srs",$i);var aj=function(a){y(this,a,"acr:rss",[])};q(aj,x);B("acr:rss",aj);var bj=function(a){y(this,a,"acr:rrs",[])};q(bj,x);B("acr:rrs",bj);var cj=function(a){y(this,a,"acr:rsr",[])};q(cj,x);B("acr:rsr",cj);var dj=function(a){y(this,a,"acr:wrs",[1])};q(dj,x);B("acr:wrs",dj);var ej=function(a){y(this,a,0,[])};q(ej,x);ej.prototype.Z=function(){return z(this,2)}; ej.prototype.Na=function(){return z(this,11)};
var fj=function(a){y(this,a,"acq:rs",[3])};q(fj,x);B("acq:rs",fj);var gj=function(a){y(this,a,0,[])};q(gj,x);var Fi=function(a){y(this,a,0,[])};q(Fi,x);Fi.prototype.Oa=function(){return Ed(this,gj,1)};var hj=function(a,b){Dd(a,1,b)},ij=function(a){y(this,a,0,[])};q(ij,x);ij.prototype.Z=function(){return z(this,1)};ij.prototype.Oa=function(){return Ed(this,gj,2)};var jj=function(a,b){Dd(a,2,b)};ij.prototype.Na=function(){return z(this,3)};
var kj=function(a){this.c=a;this.a={};this.b=a.get(bc)},lj=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")},oj=function(a,b){fe(a.reload,6E4,a);var c=[],d={},e=a.c.get(gi),f=uh(b,ej,1)||[];w(f,function(a){c.push(z(a,1));d[lj(a.Z(),a.Na())]=a});var g=c.length;c.push("viewer");mj(e,c,r(function(a){for(var c=[],e=0;e<f.length;e++){var J=a[e];if(J){var aa=f[e],K=new ij;O(K,3,aa.Na());O(K,1,aa.Z());jj(K,nj(J));c.push(K)}}wh(c,function(a,b){var c=b.Oa(),c=z(c,2),d=a.Oa();return c-z(d,2)});
w(c,function(a,b){O(d[lj(a.Z(),a.Na())],3,b)});a=a[g];e=new fj;a&&(J=new Fi,hj(J,nj(a)),Dd(e,2,J));th(e,3,c);th(b,1,f);Dd(e,1,b);this.b.set("ReloadState",e.I);V.a().b("eventReloadStateSaved",[])},a))},nj=function(a){var b=new gj;O(b,1,a.top);O(b,2,a.left);O(b,3,a.width);O(b,4,a.height);O(b,5,a.focused);O(b,6,a.state);O(b,7,a.alwaysOnTop);return b};kj.prototype.read=function(){var a=this.e;this.e=null;V.a().b("eventReloadStateRead",[a&&a.I||null])}; kj.prototype.reload=function(){M("Reloading the extension.");chrome.runtime.reload()};
var Z=function(a){this.a=new kj(a);this.b=a;chrome.runtime.onUpdateAvailable.addListener(r(this.h,this))};ga("ace.core.ExtensionLibrary",Z);Z.prototype.h=function(){M("Initiating client reload.");V.a().b("eventReloadClient",[]);fe(this.a.reload,864E5+288E5*Math.random(),this.a)};Z.prototype.p=function(a,b,c,d){a=V.b(b);null!=a&&p(d)&&d&&(d=a.j,null!=d&&null!=d.id&&(chrome.tabs.update(d.id,{selected:!0}),c&&chrome.tabs.get(d.id,function(a){Wg(a.windowId)})))};Z.prototype.selectTab=Z.prototype.p;
Z.prototype.v=function(a,b,c){c?gh(b,"width=500,height=400"):chrome.tabs.create({url:b,selected:!0},function(a){null!=a?fe(function(){chrome.tabs.get(a.id,function(a){Wg(a.windowId)})},2E3):gh(b)})};Z.prototype.openUrl=Z.prototype.v;Z.prototype.g=function(a,b){this.c=this.b.get(gi);this.c.focus(b)};Z.prototype.focusMoleByFrameId=Z.prototype.g;Z.prototype.e=function(){V.a().xb()};Z.prototype.showApplication=Z.prototype.e;Z.prototype.l=function(a,b){var c=new dj(b);oj(this.a,c)}; Z.prototype.saveReloadState=Z.prototype.l;Z.prototype.j=function(){this.a.read()};Z.prototype.readReloadState=Z.prototype.j;Z.prototype.k=function(){this.a.reload()};Z.prototype.reloadExtension=Z.prototype.k;
var pj=function(a){ji.call(this,a,7);this.c.push(new ki("join hangout"));this.c.push(new ki("ignore"))};q(pj,ji);pj.prototype.Ma=function(){var a=pj.q.Ma.call(this);return a?a:this.j?T("CHROME_EXT_GROUP_PLUS_HANGOUT_DETAILS"):T("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")};pj.prototype.xa=function(){return null!=this.e?pj.q.xa.call(this):null};
var qj=function(a,b){this.a=b||new Lh;b||(this.a.alwaysOnTop=Sg(a.get(hi).a))},sj=function(a,b,c){(b=b.k)?rj(a.get(gi),b,function(b){c(new qj(a,b))}):c(new qj(a))};var tj=function(){Ph.call(this)};q(tj,Ph);tj.prototype.setTitle=function(a){Uh(this,r(function(){Vh(this).document.title=a},this))};
var vj=function(a,b){a.t=b;Uh(a,r(function(){uj(this)},a))},wj=function(a,b){a.w=b;Uh(a,r(function(){uj(this)},a))},uj=function(a){var b=Vh(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=hh("icon-24x24.png",!0);a=[a.t||e,a.w];for(var e=fc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],k=d[g];k||(k=b.createElement("LINK"),c.appendChild(k));k.rel="shortcut icon";var n=a[g];k.type=$g(n,".ico")?"image/x-icon":$g(n,".gif")?"image/gif":"image/png";k.href=a[g]}};
var yj=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[xj(a[b])]=null;for(var c in Object.prototype);},zj={},xj=function(a){return a in zj||32==String(a).charCodeAt(0)?" "+a:a},Aj=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};h=yj.prototype;h.clear=function(){this.a={}};h.clone=function(){var a=new yj,b;for(b in this.a)a.a[b]=null;return a};h.contains=function(a){return xj(a)in this.a};h.forEach=function(a,b){for(var c in this.a)a.call(b,Aj(c),void 0,this)};
h.X=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};h.C=Object.keys?function(){return Object.keys(this.a).map(Aj,this)}:function(){var a=[],b;for(b in this.a)a.push(Aj(b));return a};h.R=function(){for(var a in this.a)return!1;return!0};h.remove=function(a){a=xj(a);return a in this.a?(delete this.a[a],!0):!1};h.ia=function(){return eh(this.C())};
var $=function(a){this.j=a;this.a={};this.c={};this.b=new yj;ga("__onPanelLoad",r(this.K,this));this.p=a.get(ci);a=new H(this);Q(this,a);a.listen(V,"onStatusChange",this.A)};q($,E);ga("ace.core.PanelsManager",$);$.prototype.n=function(){for(var a in this.a)this.pb(this.a[a]);$.q.n.call(this)};$.prototype.w=function(a,b){var c=function(a){a=a?!a.isMinimized():null;V.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?Yh(d,c):c(void 0)};$.prototype.isMaximized=$.prototype.w;
$.prototype.M=function(a,b,c,d,e,f,g,k,n,A){M("Opening a new panels with id '%s'",b);a="panel.html?"+b;d=d||T("CHROME_EXT_SHORT_NAME");b=Ei(this,b,k||b,a,d,e,g);Uh(b,r(this.k,this,c));c=new ph(280,420);n||A?(n=n||null,e=A||null,A=this.j.get(di).a,n=lj(n,e),(e=A.a[n])&&delete A.a[n],A=e?e.Oa():null):A=null;f=Gi(this,c,!!f,A);Hi(this,b.id,f)};$.prototype.openPanel=$.prototype.M;
$.prototype.B=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||T("CHROME_EXT_SHORT_NAME");b=Ei(this,b,b,a,d);Uh(b,r(this.k,this,c));c=Gi(this,new ph(f,g),e,null);c.ed=!0;Hi(this,b.id,c);return b};$.prototype.openDialog=$.prototype.B;var Ei=function(a,b,c,d,e,f,g){a.a[b]&&a.pb(a.a[b]);var k=new tj;k.id=b;k.key=c;k.url=d;k.setTitle(e);vj(k,f);wj(k,g);a.a[b]=k;a.c[c]=b;return k};$.prototype.k=function(a,b){b.p=new ai(a,Vh(b).document);Q(b,b.p)};
var Gi=function(a,b,c,d){b={focus:c,Ca:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=z(d,1);b.left=z(d,2);c=z(d,3);var e=z(d,4);z(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==z(d,6)&&(b.minimize=!0);b.Ca=z(d,7);b.focus=z(d,5)}b.Ca="boolean"==typeof b.Ca?b.Ca:Sg(a.j.get(hi).a);return b},Hi=function(a,b,c){var d=a.a[b];d.onClosed.addListener(r(a.pb,a));d.j.addListener(r(a.L,a));d.g.addListener(r(a.F,a));c.minimize&&d.minimize();b=
"panel";c.Ca||(b=bh()?"popup":"detached_panel");c.ed&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.Ca?d.create(e):mj(a,Object.keys(a.c),r(function(a){var b=screen,c;c=new ph(260,460);var n=new ph(280,420);c=new ph(Math.max(c.width,n.width),Math.max(c.height,n.height));for(var A=b.availWidth,J=b.availHeight-50,n=b.availTop+J%c.height,b=b.availLeft+A%c.width,A=Math.floor(A/c.width),aa=Math.floor(J/c.height),
J=Array(A*aa),K=0;K<a.length;K++){var la=a[K];if(la){for(var Nb=[la.left,la.left+la.width-1],la=[la.top,la.top+la.height-1],na=0;2>na;na++)Nb[na]=Math.floor(Math.max(0,Nb[na]-b)/c.width),la[na]=Math.floor(Math.max(0,la[na]-n)/c.height);for(na=Nb[0];na<=Nb[1];na++)for(var db=la[0];db<=la[1];db++)na<A&&db<aa&&(J[na+db*A]=1)}}a=J.length-1;for(K=J.length-1;0<=K;K--)if(!J[K]){a=K;break}J=a%A*c.width;e.top=n+Math.floor(a/A)*c.height+(c.height-e.height);e.left=b+J+(c.width-e.width);d.create(e)},a))};
$.prototype.h=function(a,b){var c=this.a[b];c&&F(c)};$.prototype.closePanel=$.prototype.h;$.prototype.g=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.h(0,a)};$.prototype.closeAllPanels=$.prototype.g;$.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};$.prototype.setTitle=$.prototype.setTitle;$.prototype.t=function(a,b,c){this.a[b]&&Wh(this.a[b],c)};$.prototype.drawAttention=$.prototype.t;
$.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];Yh(b,r(function(a){if(a&&(a=Vh(b),0==a.outerWidth&&0==a.outerHeight)){this.pb(b);return}b.focus()},this))}};$.prototype.S=function(a,b,c){this.a[b]&&vj(this.a[b],c)};$.prototype.setPresence=$.prototype.S;$.prototype.O=function(a,b,c){this.a[b]&&wj(this.a[b],c)};$.prototype.setAvatar=$.prototype.O;$.prototype.e=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.l(0,d,b,c);b||this.b.clear()};
$.prototype.minimizeAllPanelsIfTopmost=$.prototype.e;$.prototype.l=function(a,b,c,d){var e=this.a[b];e&&Yh(e,r(function(a){if(a&&a.alwaysOnTop&&!this.H)if(c){var g;(g=!d)||(g=new ih(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.a[xj(b)]=null)}else chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};$.prototype.minimizePanelIfTopmost=$.prototype.l;
$.prototype.K=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.e=a,Sh(b))};var rj=function(a,b,c){a=a.a[a.c[b]];!a||Qh(a)?c(void 0):Yh(a,c)},mj=function(a,b,c){var d=[];w(b,r(function(a){d.push(this.a[this.c[a]])},a));Xh(d,c)};$.prototype.pb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],F(a))};$.prototype.L=function(a){this.a[a.id]==a&&this.b.remove(a.id)};$.prototype.F=function(a){this.a[a.id]==a&&V.a().b("eventBlurred",[a.id])}; $.prototype.A=function(){3==this.p.a&&this.g()};
var Bj=function(a){this.k=a;this.a=new C;this.j=new C;this.c=new Xi(a);Q(this,this.c);this.h=r(this.hd,this);chrome.notifications.onClosed.addListener(this.h);this.e=r(this.Oc,this);chrome.notifications.onClicked.addListener(this.e);this.g=r(this.gd,this);chrome.notifications.onButtonClicked.addListener(this.g)};q(Bj,E);ga("ace.core.NotificationManager",Bj);
Bj.prototype.n=function(){w(this.a.C(),F);this.a.clear();chrome.notifications.onClosed.removeListener(this.h);chrome.notifications.onClicked.removeListener(this.e);chrome.notifications.onButtonClicked.removeListener(this.g);Bj.q.n.call(this)};
Bj.prototype.p=function(a,b){M("Parsing notification to register.");var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");c=0==c.indexOf("bc")?new oi(c):0<c.indexOf("chat")||0<=c.indexOf("voice")||0<=c.indexOf("video")?new ni(c):0==c.indexOf("hangout")?new pj(c):new ji(c,8);c.setTitle(b.Content.TitleText);c.l=b.Content.SubtitleText;c.h=b.Content.BodyText;c.e=b.Content.BodyTextId||b.Content.BodyTimestamp;c.b=b.Content.BodyTimestamp;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,
isNaN(d)||!isFinite(d))&&(d=0);d=d||m()+1E4;c.v=d;b.Content.ServiceIcon?(d=b.Content.ServiceIcon,c.g=d&&hh(d)||""):b.Content.TitleTemplate&&(d=b.Content.TitleTemplate.IconUrl,c.g=d&&hh(d)||"");b.Content.IsGroupChat&&(c.j=!0);b.Content.FrameId&&(c.k=b.Content.FrameId);if(b.Content.BodyTemplate)for(var d=b.Content.BodyTemplate.Action,e=0;e<d.length;e++)d[e].Name&&c.c.push(new ki(d[e].Name,d[e].Text))}else M("Failed to parse the notifications sent from the page."),c=null;if(c)if(V.a().b("eventLogImpression",
["qnop"]),M("Duplicate detection and registration."),Yi(this.c,c))M("Dropping duplicate notification id="+c.a+", detailId="+c.e),Cj(c.a,"toastEventOnNotDisplayed");else{var d=this.c,e=c,f=e.xa();if(null!=f&&!Yi(d,e))switch(e.type()){case 7:case 2:null!=e.b&&d.b<e.b&&(d.b=e.b,d.c.set("dupDetectionQueue.latestChat",d.b)),d.g.set(f,m()+18E5)}Dj(this,c)}};Bj.prototype.registerNotification=Bj.prototype.p;
var Dj=function(a,b){2==b.type()||b.k?sj(a.k,b,function(c){c=c.a;c.focused||c.alwaysOnTop?Cj(b.a,"toastEventOnNotDisplayed"):Ej(a,b)}):Ej(a,b)},Ej=function(a,b){var c=b.a,d=b.v-m();0>=d?a.lc(c):(M("Notification is getting registered: "+c),a.a.set(c,b),chrome.notifications.create(c,mi(b),function(){V.a().b("eventLogImpression",["qtod"])}),ge(a.j.get(c,null)),b.v!=Number.MAX_VALUE&&a.j.set(c,fe(r(a.lc,a,c),d)),V.a().b("eventLogImpression",["qnst"]))};
Bj.prototype.b=function(){w(sa(this.a.C(),Tg),this.Ia,this)};Bj.prototype.cleanAllNotifications=Bj.prototype.b;Bj.prototype.l=function(a,b){M("Clean a notification: "+b);var c=this.a.get(b);c&&this.Ia(c)};Bj.prototype.cleanANotification=Bj.prototype.l;h=Bj.prototype;h.Ia=function(a){a=a.a;M("Closing a toast: "+a);chrome.notifications.clear(a,ka);this.a.remove(a)};
h.hd=function(a,b){if(b){var c=this.a.get(a);c&&(this.a.remove(a),M("Notification toast has closed: "+a),c.Lb()?Cj(a,"toastEventOnButton","ignore"):Cj(a,"toastEventOnClose"))}};h.Oc=function(a){var b=this.a.get(a);b&&(Cj(a,"toastEventOnBody"),this.Ia(b))};h.gd=function(a,b){var c=this.a.get(a);c&&(Cj(a,"toastEventOnButton",c.c[b].name),this.Ia(c))};h.lc=function(a){var b=this.a.get(a);b&&(Cj(a,"toastEventOnTimeout"),this.Ia(b))}; var Cj=function(a,b,c){var d=V;(d=d&&d.a())&&!d.H&&V.a().b(b,[a,c,"",!1])};
var Fj=function(a){y(this,a,"f.mt",[])};q(Fj,x);B("f.mt",Fj);var Gj=function(a){y(this,a,"er",[])};q(Gj,x);B("er",Gj);Gj.prototype.Hb=function(){return z(this,9)};Gj.prototype.getData=function(){return z(this,4)};new rh;D&&Ua(8);var Hj=function(){throw Error("A");};Hj.prototype.a=null;Hj.prototype.toString=function(){return this.content};var Ij=function(){Hj.call(this)};q(Ij,Hj);(function(a){function b(){}b.prototype=a.prototype;return function(a,d){if(!String(a))return"";var e=new b;e.content=String(a);void 0!==d&&(e.a=d);return e}})(Ij);var Jj=function(a,b){Tc.call(this,a,b)};q(Jj,Tc);var Kj=function(a){this.a=a?z(a,1)||-1:-1},Lj=new Kj;var Mj=function(){};q(Mj,ke);Mj.prototype.b=function(){};Mj.prototype.b.rc=!0;Mj.q||q(Mj,ke);U.a={};U.a.vb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";U.a.tb=U.a.vb+"0123456789";U.a.wb=U.a.vb.length;U.a.ub=U.a.tb.length;U.a.Ub=-2147483648;U.a.xd=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?U.a.wb:U.a.ub)+U.a.tb.indexOf(a.charAt(c));return b+U.a.Ub};U.a.toString=function(a){var b=[],c=0;a-=U.a.Ub;b[c++]=U.a.vb.charAt(a%U.a.wb);for(a=Math.floor(a/U.a.wb);0<a;)b[c++]=U.a.tb.charAt(a%U.a.ub),a=Math.floor(a/U.a.ub);return b.join("")};
new Jj(Vc,"f_req");
}catch(e){_DumpException(e)}
try{
var zm=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||l;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",g;for(g in a)f=a[g],null!=f&&!ha(f)&&(e+=encodeURIComponent(g)+"="+encodeURIComponent(f)+"&");g=d.document;d=g.createElement("script");d.src=e;g.body.appendChild(d)}}; ga("userfeedback.api.startFeedback",zm);
var Am=function(){H.call(this);this.listen(window,"unload",this.D);document.title=T("CHROME_EXT_SHORT_NAME")+": "+T("CHROME_EXT_FEEDBACK_SUBTITLE");S("system-legend").innerText=T("QUASAR_FEEDBACK_SYSTEM_LEGEND");S("system-platform-label").innerText=T("QUASAR_FEEDBACK_PLATFORM_LABEL");S("system-platform-value").innerText=navigator.platform;S("system-user-agent-label").innerText=T("QUASAR_FEEDBACK_USER_AGENT_LABEL");S("system-user-agent-value").innerText=navigator.userAgent;S("user-legend").innerText=
T("CHROME_EXT_FEEDBACK_COMMENTS");S("privacy-legend").innerText=T("QUASAR_FEEDBACK_PRIVACY_LEGEND");S("privacy-text").innerText=T("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=S("submit-button");a.innerText=T("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=S("cancel-button");a.innerText=T("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);S("user-text-value").focus()};q(Am,H);
Am.prototype.b=function(){var a=S("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:T("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:chrome.runtime.getManifest().version,build:chrome.runtime.id};S("submit-button").disabled=!0;zm(a,b)}};Am.prototype.a=function(){window.close()};window.addEventListener("load",function(){new Am},!1);

}catch(e){_DumpException(e)}
// Google Inc.
