try{
var h,ba=ba||{},l=this,ca="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
l.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"}, quasar_sign_in:{message:"Sign in"}};

}catch(e){_DumpException(e)}
try{
var p=function(a){return void 0!==a},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;
a.q=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Gd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(ma,Error);ma.prototype.name="CustomError";
var pa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",n=e[g]||"",A=RegExp("(\\d*)(\\D*)","g"),J=RegExp("(\\d*)(\\D*)","g");do{var aa=A.exec(k)||["","",""],K=J.exec(n)||["","",""];if(0==aa[0].length&&0==K[0].length)break;c=oa(0==aa[1].length?0:parseInt(aa[1],10),0==K[1].length?0:parseInt(K[1],10))||oa(0==aa[2].length,0==K[2].length)||oa(aa[2], K[2])}while(0==c)}return c},oa=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,qa=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var n=g[k];b.call(c,n,k,a)&&(e[f++]=n)}return e},ta=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,
f[g],g,a));return e},ua=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,g){e=b.call(d,e,c,g,a)});return e},va=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},wa=function(a,b){var c=qa(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var xa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var ya=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},za=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.I=b;t:{if(a.I.length&&(b=a.I.length-1,(c=a.I[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.e=b-a.b;a.c=c;break t}a.e=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.e?(c+=a.b,a.I[c]=a.I[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.e?a.I[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.I.toString()};var B=function(a,b){Ba[a]=b;b.Nb=a},Ba={};
var Ca="StopIteration"in l?l.StopIteration:Error("f"),Da=function(){};Da.prototype.next=function(){throw Ca;};Da.prototype.ia=function(){return this};var Ea;t:{var Fa=l.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){Ea=Ga;break t}}Ea=""}var Ha=function(a){return-1!=Ea.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.e=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.N(),d=a.C()):(c=Aa(a),d=za(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};h=C.prototype;h.X=function(){return this.c};h.C=function(){Ia(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};h.N=function(){Ia(this);return this.b.concat()};h.R=function(){return 0==this.c};
h.clear=function(){this.a={};this.e=this.c=this.b.length=0};h.remove=function(a){return Ja(this.a,a)?(delete this.a[a],this.c--,this.e++,this.b.length>2*this.c&&Ia(this),!0):!1};var Ia=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ja(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ja(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};h=C.prototype;h.get=function(a,b){return Ja(this.a,a)?this.a[a]:b};
h.set=function(a,b){Ja(this.a,a)||(this.c++,this.b.push(a),this.e++);this.a[a]=b};h.forEach=function(a,b){for(var c=this.N(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new C(this)};h.ia=function(a){Ia(this);var b=0,c=this.b,d=this.a,e=this.e,f=this,g=new Da;g.next=function(){for(;;){if(e!=f.e)throw Error("i");if(b>=c.length)throw Ca;var g=c[b++];return a?g:d[g]}};return g};var Ja=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Ka=function(a){if("function"==typeof a.C)return a.C();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return za(a)},La=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.N)d=a.N();else if("function"!=typeof a.C)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Aa(a);else d=void 0;for(var e=Ka(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Ma=Ha("Opera")||Ha("OPR"),D=Ha("Trident")||Ha("MSIE"),Na=Ha("Gecko")&&-1==Ea.toLowerCase().indexOf("webkit")&&!(Ha("Trident")||Ha("MSIE")),Oa=-1!=Ea.toLowerCase().indexOf("webkit"),Pa=l.navigator||null,Qa=Pa&&Pa.platform||"",Ra=function(){var a=l.document;return a?a.documentMode:void 0},Sa=function(){var a="",b;if(Ma&&l.opera)return a=l.opera.version,s(a)?a():a;Na?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Oa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Ea))?a[1]:"");return D&&(b= Ra(),b>parseFloat(a))?String(b):a}(),Ta={},Ua=function(a){return Ta[a]||(Ta[a]=0<=pa(Sa,a))},Va=l.document,Wa=Va&&D?Ra()||("CSS1Compat"==Va.compatMode?parseInt(Sa,10):5):void 0;
var E=function(){};E.prototype.H=!1;E.prototype.Kb=function(){return this.H};E.prototype.D=function(){this.H||(this.H=!0,this.n())};E.prototype.n=function(){if(this.v)for(;this.v.length;)this.v.shift()()};var F=function(a){a&&"function"==typeof a.D&&a.D()};
var Xa=!D||D&&9<=Wa;!Na&&!D||D&&D&&9<=Wa||Na&&Ua("1.9.1");D&&Ua("9");var Ya=function(a){Ya[" "](a);return a};Ya[" "]=ka;var Za=function(a,b){try{return Ya(a[b]),!0}catch(c){}return!1};var $a=!D||D&&9<=Wa,ab=D&&!Ua("9");!Oa||Ua("528");Na&&Ua("1.9b")||D&&Ua("8")||Ma&&Ua("9.5")||Oa&&Ua("528");Na&&!Ua("8")||D&&Ua("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.yc=!0};G.prototype.D=function(){};G.prototype.b=function(){this.yc=!1};var bb=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Na&&Za(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};q(bb,G); bb.prototype.b=function(){bb.q.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ab)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var cb="closure_listenable_"+(1E6*Math.random()|0),eb=function(a){return!(!a||!a[cb])},fb=0;var gb=function(a,b,c,d,e){this.ra=a;this.proxy=null;this.src=b;this.type=c;this.cb=!!d;this.kb=e;this.key=++fb;this.removed=this.bb=!1},hb=function(a){a.removed=!0;a.ra=null;a.proxy=null;a.src=null;a.kb=null};var ib=function(a){this.src=a;this.a={};this.b=0},kb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=jb(b,c,e,f);-1<k?(a=b[k],d||(a.bb=!1)):(a=new gb(c,a.src,g,!!e,f),a.bb=d,b.push(a));return a};ib.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=jb(e,b,c,d);return-1<b?(hb(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var lb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=wa(a.a[c],b);d&&(hb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};ib.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,hb(d[e]);delete this.a[c];this.b--}return b}; var mb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=jb(a,c,d,e));return-1<b?a[b]:null},jb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.ra==b&&f.cb==!!c&&f.kb==d)return e}return-1};
var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0,qb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);return null}c=rb(c);return eb(a)?a.listen(b,c,d,e):sb(a,b,c,!1,d,e)},sb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,k=tb(a);k||(a[nb]=k=new ib(a));c=kb(k,b,c,d,e,f);if(c.proxy)return c;d=ub();c.proxy=d;d.src=a;d.ra=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(vb(b.toString()),d);pb++;return c},ub=function(){var a=wb,b=$a?function(c){return a.call(b.src,
b.ra,c)}:function(c){c=a.call(b.src,b.ra,c);if(!c)return c};return b},xb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);else c=rb(c),eb(a)?a.Tb(b,c,d,e):a&&(a=tb(a))&&(b=mb(a,b,c,!!d,e))&&yb(b)},yb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(eb(b))return lb(b.W,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.cb):b.detachEvent&&b.detachEvent(vb(c),d);pb--;(c=tb(b))?(lb(c,a),0==c.b&&(c.src=null,b[nb]=null)):hb(a);return!0},vb=function(a){return a in
ob?ob[a]:ob[a]="on"+a},Ab=function(a,b,c,d){var e=1;if(a=tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.cb==c&&!f.removed&&(e&=!1!==zb(f,d))}return Boolean(e)},zb=function(a,b){var c=a.ra,d=a.kb||a.src;a.bb&&yb(a);return c.call(d,b)},wb=function(a,b){if(a.removed)return!0;if(!$a){var c;if(!(c=b))t:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new bb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;0<=k;k--)c.a=e[k],d&=Ab(e[k],f,!0,c);for(k=0;k<e.length;k++)c.a=e[k],d&=Ab(e[k],f,!1,c)}return d}return zb(a,new bb(b,this))},tb=function(a){a=a[nb];return a instanceof ib?a:null},Bb="__closure_events_fn_"+(1E9*Math.random()>>>0),rb=function(a){return s(a)?a:a[Bb]||(a[Bb]=function(b){return a.handleEvent(b)})};
var Cb=function(a){y(this,a,"h_cc",[])};q(Cb,x);B("h_cc",Cb);Cb.prototype.Z=function(){return z(this,19)};var H=function(a){this.L=a;this.h={}};q(H,E);var Db=[];H.prototype.listen=function(a,b,c,d){return Eb(this,a,b,c,d)};var Eb=function(a,b,c,d,e,f){u(c)||(c&&(Db[0]=c.toString()),c=Db);for(var g=0;g<c.length;g++){var k=qb(b,c[g],d||a.handleEvent,e||!1,f||a.L||a);if(!k)break;a.h[k.key]=k}return a};
H.prototype.Tb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Tb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.L||this,c=rb(c),d=!!d,b=eb(a)?mb(a.W,String(b),c,d,e):a?(a=tb(a))?mb(a,b,c,d,e):null:null,b&&(yb(b),delete this.h[b.key]);return this};H.prototype.removeAll=function(){ya(this.h,yb);this.h={}};H.prototype.n=function(){H.q.n.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){this.W=new ib(this);this.O=this;this.w=null};q(I,E);I.prototype[cb]=!0;h=I.prototype;h.addEventListener=function(a,b,c,d){qb(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){xb(this,a,b,c,d)};h.n=function(){I.q.n.call(this);this.W&&this.W.removeAll(void 0);this.w=null};h.listen=function(a,b,c,d){return kb(this.W,String(a),b,!1,c,d)};h.Tb=function(a,b,c,d){return this.W.remove(String(a),b,c,d)}; h.ea=function(a,b,c){a=this.W.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.cb==b){var g=f.ra,k=f.kb||f.src;f.bb&&lb(this.W,f);d=!1!==g.call(k,c)&&d}}return d&&!1!=c.yc};
var Fb,Gb,Hb,Ib,Jb,Kb,Lb;Lb=Kb=Jb=Ib=Hb=Gb=Fb=!1;var Mb=Ea;Mb&&(-1!=Mb.indexOf("Firefox")?Fb=!0:-1!=Mb.indexOf("Camino")?Gb=!0:-1!=Mb.indexOf("iPhone")||-1!=Mb.indexOf("iPod")?Hb=!0:-1!=Mb.indexOf("iPad")?Ib=!0:-1!=Mb.indexOf("Chrome")?Kb=!0:-1!=Mb.indexOf("Android")?Jb=!0:-1!=Mb.indexOf("Safari")&&(Lb=!0));var Ob=Fb,Pb=Gb,Qb=Hb,Rb=Ib,Sb=Jb,Tb=Kb,Ub=Lb;
var L=function(a){this.a=a};L.prototype.toString=function(){return this.a};var Vb=new L("b"),Wb=new L("c"),Xb=new L("h"),Yb=new L("k"),Zb=new L("G"),$b=new L("M"),ac=new L("N");var bc=new L("ea");var dc=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("o");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,A,J,aa){if("%"==A)return"%";var K=c.shift();if("undefined"==typeof K)throw Error("p");arguments[0]=K;return cc[A].apply(null,arguments)})},cc={s:function(a,b,c){return isNaN(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+Array(c-a.length+1).join(" "):Array(c-a.length+1).join(" ")+a},f:function(a,b,c,
d,e){d=a.toString();isNaN(e)||""==e||(d=a.toFixed(e));var f;f=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=f+d);if(isNaN(c)||d.length>=c)return d;d=isNaN(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=c-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Array(a+1).join(" "):f+Array(a+1).join(0<=b.indexOf("0",0)?"0":" ")+d},d:function(a,b,c,d,e,f,g,k){return cc.f(parseInt(a,10),b,c,d,0,f,g,k)}};cc.i=cc.d;cc.u=cc.d;
var ec=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},M=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=dc("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+dc(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+dc.apply({},c)))},fc=function(){return 0<=navigator.userAgent.indexOf("CrOS")};
var gc=function(a,b){this.e=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.g=null;this.j=b||"u";this.a=this.v=null;this.h=[]};gc.prototype.message=function(){var a={};a.i=this.a;a.m=this.h;a.r=this.j;a.o=this.v;a.s=this.b;a.st=this.c;a.d=this.g;a.dt=this.e;return a};ga("ace.base.Message.prototype.message",gc.prototype.message);
var hc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.a=b[c];break;case "m":a.h=b[c];break;case "o":a.v=b[c];break;case "s":a.b=b[c];break;case "d":a.g=b[c];break;case "st":a.c=b[c];break;case "dt":a.e=b[c]}return a},ic=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))},jc=function(a,b){null!=b&&(a.a=b)},kc=function(a,b){"object"==typeof b?a.h=b:a.h=[b]};gc.prototype.source=function(){return this.b};gc.prototype.target=function(){return this.g};gc.prototype.Ac=function(){return this.c}; gc.prototype.content=function(){return this.h};
var lc=function(a,b,c,d,e){this.b=a;this.Ua=b;this.a=typeof b;this.Ob=c?c:!1;this.ca=!0;this.Ib=d?d:!1;this.Bb=e?e:!1};q(lc,E);h=lc.prototype;h.n=function(){lc.q.n.call(this);this.b="";this.Ua=null;this.a=""};h.id=function(){return this.b};h.type=function(){return this.a};h.G=function(){return this.Ua};h.setEnabled=function(a){this.ca=a};
var mc=function(a){return(a=a.exec(Ea))?a[1]:""},nc=function(){if(Ob)return mc(/Firefox\/([0-9.]+)/);if(D||Ma)return Sa;if(Tb)return mc(/Chrome\/([0-9.]+)/);if(Ub)return mc(/Version\/([0-9.]+)/);if(Qb||Rb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ea))return a[1]+"."+a[2]}else{if(Sb)return(a=mc(/Android\s+([0-9.]+)/))?a:mc(/Version\/([0-9.]+)/);if(Pb)return mc(/Camino\/([0-9.]+)/)}return""}();
var pc=function(a){this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&oc(this,a)};q(pc,E);var qc=0<=pa(nc,"23.0.1262.0")&&!fc();pc.prototype.n=function(){pc.q.n.call(this);for(var a=this.a.N(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};pc.prototype.getItem=function(a){return Ja(this.a.a,a)?this.a.get(a):null};pc.prototype.setItem=function(a){this.a.set(a.id(),a)}; var oc=function(a,b){for(var c in b){var d=b[c],e=null;Ja(a.a.a,c)?(e=a.a.get(c),e.Ua=d.value,d.changed&&(e.Bb=d.changed)):(e=new lc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var rc=function(a){l.setTimeout(function(){throw a;},0)},uc=function(a,b){var c=a;b&&(c=r(a,b));s(l.setImmediate)?l.setImmediate(c):(sc||(sc=tc()),sc(c))},sc,tc=function(){if(l.Promise&&l.Promise.resolve){var a=l.Promise.resolve();return function(b){a.then(function(){try{b()}catch(a){rc(a)}})}}var b=l.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";
document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.ac;d.ac=null;a()};return function(a){e.next=
{ac:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};
var zc=function(a,b){vc||(uc(wc),vc=!0);xc.push(new yc(a,b))},vc=!1,xc=[],wc=function(){for(;xc.length;){var a=xc;xc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){rc(d)}}}vc=!1},yc=function(a,b){this.a=a;this.b=b};var Ac=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Bc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Dc=function(a,b){this.b=0;this.h=void 0;this.a=this.c=null;this.e=this.g=!1;try{var c=this;a.call(b,function(a){Cc(c,2,a)},function(a){Cc(c,3,a)})}catch(d){Cc(this,3,d)}},Fc=function(){var a,b=new Dc(function(b){a=b});return new Ec(b,a)};Dc.prototype.then=function(a,b,c){return Gc(this,s(a)?a:null,s(b)?b:null,c)};Ac(Dc);
var Jc=function(a){0==a.b&&zc(function(){var a=new Hc(void 0);Ic(this,a)},a)},Ic=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.eb)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?Ic(c,b):(d=c.a.splice(e,1)[0],Kc(c,d,3,b)))}}else Cc(a,3,b)},Mc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||Lc(a);a.a||(a.a=[]);a.a.push(b)},Gc=function(a,b,c,d){var e={eb:null,tc:null,vc:null};e.eb=new Dc(function(a,g){e.tc=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){g(A)}}:
a;e.vc=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof Hc?g(b):a(e)}catch(A){g(A)}}:g});e.eb.c=a;Mc(a,e);return e.eb};Dc.prototype.v=function(a){this.b=0;Cc(this,2,a)};Dc.prototype.j=function(a){this.b=0;Cc(this,3,a)};
var Cc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(Bc(c)){a.b=1;c.then(a.v,a.j,a);return}if(ha(c))try{var d=c.then;if(s(d)){Nc(a,c,d);return}}catch(e){b=3,c=e}}a.h=c;a.b=b;Lc(a);3!=b||c instanceof Hc||Oc(a,c)}},Nc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.v(b))},f=function(b){d||(d=!0,a.j(b))};try{c.call(b,e,f)}catch(g){f(g)}},Lc=function(a){a.g||(a.g=!0,zc(a.k,a))};
Dc.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)Kc(this,a[b],this.b,this.h)}this.g=!1};var Kc=function(a,b,c,d){if(2==c)b.tc(d);else{for(;a&&a.e;a=a.c)a.e=!1;b.vc(d)}},Oc=function(a,b){a.e=!0;zc(function(){a.e&&Pc.call(null,b)})},Pc=rc,Hc=function(a){ma.call(this,a)};q(Hc,ma);Hc.prototype.name="cancel";var Ec=function(a,b){this.b=a;this.a=b};
var Sc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Qc;this.b=!0;Rc(this)};Sc.wa=function(){return Sc.a?Sc.a:Sc.a=new Sc};var Rc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){var b=chrome.runtime?chrome.runtime.lastError:void 0;b&&M("chrome storage read error "+b);if(!this.b){for(var f in a)this.c.set(f,a[f]);this.b=!0}c()},a))};Sc.prototype.get=function(a){return this.a.get(a)};Sc.prototype.set=function(a,b){var c=Fc();this.a.set(a,b);c.a(void 0);return c.b};
Sc.prototype.remove=function(a){this.a.remove(a)};Sc.prototype.clear=function(){this.a.clear()};var Qc=function(){this.a=window.localStorage};Qc.prototype.clear=function(){this.a.clear()};Qc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ba[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a}; Qc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.I,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Qc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Tc=function(a,b){this.b=a;this.a=b;this.constructor.Zb||(this.constructor.Zb={});this.constructor.Zb[this.toString()]=this};Tc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var N=function(a,b){Tc.call(this,a,b)};q(N,Tc);var Uc=function(a){this.a=a},Vc=new Uc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Wc=function(a,b){this.e=[];this.w=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.h=!1;this.g=0;this.j=null;this.t=0};Wc.prototype.k=function(a,b){this.h=!1;Xc(this,a,b)};var Xc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Yc(a)},$c=function(a){if(a.a){if(!a.l)throw new Zc;a.l=!1}};Wc.prototype.v=function(a){$c(this);Xc(this,!0,a)};var ad=function(a,b,c,d){a.e.push([b,c,d]);a.a&&Yc(a)};
Wc.prototype.then=function(a,b,c){var d,e,f=new Dc(function(a,b){d=a;e=b});ad(this,d,function(a){"undefined"!=typeof bd&&a instanceof bd?Jc(f):e(a)});return f.then(a,b,c)};Ac(Wc);
var cd=function(a){return va(a.e,function(a){return s(a[1])})},Yc=function(a){if(a.g&&a.a&&cd(a)){var b=a.g,c=dd[b];c&&(l.clearTimeout(c.gb),delete dd[b]);a.g=0}a.j&&(a.j.t--,delete a.j);for(var b=a.c,d=c=!1;a.e.length&&!a.h;){var e=a.e.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var k=f.call(e||a.w,b);p(k)&&(a.b=a.b&&(k==b||k instanceof Error),a.c=b=k);Bc(b)&&(d=!0,a.h=!0)}catch(n){b=n,a.b=!0,cd(a)||(c=!0)}}a.c=b;d&&(k=r(a.k,a,!0),d=r(a.k,a,!1),b instanceof Wc?(ad(b,k,d),b.p=!0):b.then(k,d));c&&
(b=new ed(b),dd[b.gb]=b,a.g=b.gb)},Zc=function(){ma.call(this)};q(Zc,ma);Zc.prototype.message="Deferred has already fired";Zc.prototype.name="AlreadyCalledError";var ed=function(a){this.gb=l.setTimeout(r(this.b,this),0);this.a=a};ed.prototype.b=function(){delete dd[this.gb];throw this.a;};var dd={};

}catch(e){_DumpException(e)}
try{
var fd=function(){return chrome.runtime.getURL("feedbackdialog.html")},gd=function(a,b){for(var c=t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};var id=function(a){this.c={};this.j={};this.k={};this.e={};this.l={};this.t={};this.p=a?a.va():new I;this.B=!a;this.g=null;a?(this.g=a,this.k=a.k,this.e=a.e,this.j=a.j,this.l=a.l):m();a=hd(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};q(id,E);var hd=function(a){for(;a.g;)a=a.g;return a};id.prototype.get=function(a){var b=this.b(a);if(null==b)throw new jd(a);return b};
id.prototype.b=function(a){for(var b=this;b;b=b.g){if(b.H)throw Error("q");if(b.c[a])return b.c[a][0];if(b.t[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};id.prototype.a=function(a,b,c){if(this.H)c||F(b);else{this.c[a]=[b,!c];b=kd(this,this,a);for(c=0;c<b.length;c++)b[c].v(null);delete this.j[a]}};id.prototype.w=function(){var a=ld;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&F(b[0])};
var kd=function(a,b,c){var d=[],e=a.e[c];e&&(gd(e,function(a){var c;t:{for(c=a.$b;c;){if(c==b){c=!0;break t}c=c.g}c=!1}c&&(d.push(a.Hd),wa(e,a))}),0==e.length&&delete a.e[c]);return d},md=function(a,b){a.e&&La(a.e,function(a,d,e){gd(a,function(d){d.$b==b&&wa(a,d)});0==a.length&&delete e[d]})};
id.prototype.n=function(){if(hd(this)==this){var a=this.h;if(a)for(;a.length;)a[0].D()}else for(var a=hd(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].D&&a[0].D();this.c=null;this.B&&this.p.D();md(this,this);this.e=null;F(this.A);this.t=this.A=null;id.q.n.call(this)};id.prototype.va=function(){return this.p};var jd=function(a){ma.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};q(jd,ma); var nd=new Uc("fva");new N(nd,1);

}catch(e){_DumpException(e)}
try{
var Qg=function(a){for(var b=a.a.N(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.G(),type:f.type(),multiple:f.Ob,disabled:!f.ca,inverse:f.Ib,changed:f.Bb}}return c},Rg=function(a,b){return t(b)?a.getElementById(b):b},S=function(a){return Rg(document,a)},T=function(a){var b;b=b||[];b.length||(b[0]="");var c=chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=l.ace_i18n[a.toLowerCase()])?c.message:l.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_DumpException(e)}
try{
var Bm=function(){var a=S("fieldsetDestPage");a&&a.parentNode&&a.parentNode.removeChild(a)},Cm=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},Dm=function(a){this.e=ec("setting",""+m());this.c=null;this.b=new H;this.a=new C;this.g=a.get(bc);this.b.listen(window,"unload",this.D)};q(Dm,E);ga("ace.ui.SettingsDialog",Dm);ga("ace.ui.SettingsDialog",Dm);
Dm.prototype.j=function(){document.title=T("CHROME_EXT_SHORT_NAME");this.c=chrome.runtime.connect({name:this.e});var a=this;this.c.onMessage.addListener(function(b){switch(hc(new gc,b).a){case "focus":Gm(a);a.sendMessage("extensionLibrary",["selectTab",a.e,!0,!0]);window.focus();break;case "close":a.h()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",["TrayIcon",1]);Bm();Hm("legendApp",
T("QUASAR_LEGEND_STARTUP_SHUTDOWN"));Hm("legendNotice",T("QUASAR_LEGEND_NOTIFICATIONS"));Im(this,"StartOnBrowserLaunch",T("CHROME_EXT_RUN_AT_BROWSER_START"));Im(this,"StopOnBrowserClose",T("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));Im(this,"TrayIcon",T("QUASAR_LABEL_TRAY_ICON"));qc?Im(this,"TopMost",T("CHROME_EXT_NEW_WINDOWS_TOPMOST")):Jm(this,"TopMost");fc()&&Jm(this,"TrayIcon");Gm(this);var b=S("feedbackLink");b.innerText=T("CHROME_EXT_MENUTEXT_FEEDBACK");b.href=fd();b=S("helpLink");b.innerText=T("QUASAR_HELP");
b.href=Cm("https://support.google.com/hangouts?p=help&hl=%s",chrome.i18n.getMessage("@@ui_locale"));this.l=S("buttonSave");this.l.innerText=T("QUASAR_BUTTON_SAVE");this.b.listen(this.l,"click",r(this.p,this),!1);this.k=S("buttonCancel");this.k.innerText=T("QUASAR_BUTTON_CANCEL");this.b.listen(this.k,"click",r(this.h,this),!1)};Dm.prototype.init=Dm.prototype.j;Dm.prototype.n=function(){Dm.q.n.call(this);F(this.b)};
var Km=function(a,b,c){var d=[];b=b+a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(S(b+c));else d.push(S(b));return d},Gm=function(a){for(var b=new pc(a.g.get("settings")),c=a.a.N(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=Km(a,"field",c[d]);if(e.Ob){var g=e.G();0<=g&&f[g]&&(f[g].checked=!0)}else f[0]&&("boolean"==e.a?e.Ib?f[0].checked=!e.G():f[0].checked=e.G():f[0].value=e.G());if(!e.ca)for(e=Km(a,"label",c[d]),g=0;g<e.length;g++)e[g]&&(e[g].disabled=!0),f[g]&&(f[g].disabled=
!0)}}},Hm=function(a,b){var c=S(a);c&&(c.innerText=b)},Im=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=S("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=S("label"+d))&&c&&(e.innerText=c)},Jm=function(a,b){var c=a.a.get(b)[0],d=S("field"+c);(d=(c=(c=S("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
Dm.prototype.p=function(){for(var a=new pc(this.g.get("settings")),b=this.a.N(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=Km(this,"field",b[c]),f=d.G();if(d.Ob){for(var g=-1,k=0;k<e.length;k++)if(e[k]&&e[k].checked){g=k;break}-1==g&&(g=0);d.Ua=g}else e[0]?d.Ua="boolean"==d.a?d.Ib?!e[0].checked:e[0].checked:e[0].value:M("Field "+c+" not found.");f!=d.G()&&(d.Bb=!0,a.setItem(d))}}this.g.set("settings",Qg(a));this.h()};
Dm.prototype.h=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()};Dm.prototype.sendMessage=function(a,b,c){c=c?c:""+m();var d=new gc;ic(d,this.e,"p");null!=a&&(d.v=a);jc(d,c);kc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){Rc(Sc.wa(),function(){var a=new id;a.a(bc,Sc.wa());(new Dm(a)).j()})},!1);
}catch(e){_DumpException(e)}
// Google Inc.
